{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 数据处理"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "利用Dataset类加载数据， 自定义的数据集需要继承Dataset，并实现__getitem__ 和 __len__ 方法。\n",
    "\n",
    "torchvision.transforms 模块实现了对PIL Image对象和Tensor对象的常用操作。"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from  PIL import Image\n",
    "import numpy as np\n",
    "from torch.utils import data\n",
    "from torchvision import transforms as T"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "transform = T.Compose([\n",
    "    T.Resize(224), T.CenterCrop(224),\n",
    "    T.ToTensor(), T.Normalize(mean = [.5, .5, .5], std = [.5, .5, .5])\n",
    "])\n",
    "\n",
    "class DogCat(data.Dataset):\n",
    "    def __init__(self, root, transforms=None):\n",
    "        imgs = os.listdir(root)\n",
    "        self.imgs = [os.path.join(root, img) for img in imgs]\n",
    "        self.transforms = transforms\n",
    "        \n",
    "    def __getitem__(self, index):\n",
    "        img_path = self.imgs[index]\n",
    "        label = 0 if 'dog' in img_path.split('/')[-1] else 1\n",
    "        data = Image.open(img_path)\n",
    "        if self.transforms:\n",
    "            data = self.transforms(data)\n",
    "        return data, label\n",
    "    \n",
    "    def __len__(self):\n",
    "        return len(self.imgs)\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 视觉工具包 torchvision\n",
    "\n",
    "包含三个部分：\n",
    "\n",
    "models: 提供各种经典网络结构和模型\n",
    "\n",
    "datasets： 提供常用的数据集加载\n",
    "\n",
    "transforms： 提供常用的数据预处理操作\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAwS0lEQVR4nAFAML/PAWYEoRrauCzQwihQQI0Qs8fwWb5DbIWKGzJPBd7V258bZArW01s+LvVG3kPcgWTnjTrTcSZHF0zGLXSKmR7aInox9GkJosCfzGfr3OfZSXGYRQoJkHQVq4jCSLt5NapwrEhEGno/rmux5tFkoJV7pKjdBQFk8IUCOQRoYXPBqitzh3AD5QyCtMFK6/52z8ZD5WjGI/AASL/EPV9LjrN5bYCI+Z6oFTEwEFQC5hBDKO+vCgLg0g0JsOKvIhGHrXcG6AG1zyzgdYVXcvdqenHcEpF1dElbRotqlZ5d3da/+bQ9e9g6mQTpQSj31FgiJVlBiEorNivwS7e+QpuYpiiSTQA8C/5F+SAto38PiHtgEG4A4d0kU1MGNWh57T062mRFAfyq7a0p+MrqSHPzYuI94NaOJYDWXbsk4K9jx0jO55rClzu56nE87MATBO/AEgnLvptg+mwBvotJGJfBEgytDLHbDLDIgp9aymtfMQe/qP7/u1Yfz2/P0RUd5VDoZgSLaoUCROCj1p9HhocTFc+OHfN6QtjaWmblIQh0PzIAFeaXYUbPmFAnLNSPnhigStMdennflQ/vg1cNv95uwZxMFUFQSN0t4B9/8xTfihH84TMTlWLq+U57BvrcsBlwn+ZH5xg5IWwggb/vWlPHEuBq8MSazazJW6aqR4xi9QTdMQxpOaCWnDhHWslMr0WFVXWkOE7jzEj2nCMGoVlN3pTBzfMdzbI1feEQQkj3GbWVsH5IN0zuxXh3FPJFV0h1+XF5cL6jAWjPe5S0iMwcQvDiD7kNssmFOUJW5NHmha/LL8AlRSnAku2Nkd3uNmzrI+npifvaazJZ0r9ipbH63xZAbr2MelQzVovuHUWaWf6V7dZous10I0IKeEAmbkISUt2yJtBdNAHlOihgZEHV6toFCyxZXGVzRC5S4CnwS4a/srZ0p1ZldDCeSfCu8x3pUlsLEzjnWAj2SMjAX7rqvrXAdw0otKfX0zLixkbGI9D2MoJ45vzK6rgdAQfr9MkHhPimcDLWbQIBlqIEHoghvs46go9d7wzzCPQxs9Kq3+pXAaLxx9AOTute7V54cesWyiTknyD1fnunNH2EpO9ZEyHN1ZW0yLWhvl9gY720G9CwW8gnIgZeoT6d46ZYZqCgJNpY+1bAwTWo4Mg1XwxoPiZqbLUTNmz7S6B+V6DO7v/TrHtVCD9OX149lxPUf1xCaVUHPhEa4PoormnvB0P21xgI3hTRZqnhWlBy3tjWihhk93nYvFGE6jCN8POhlMSPLzFM0He2PvgAI4iuCexZhNK8ZOip1mLepNMKTjeBtGkO2I+UdiCtCD2wLgc037q0KPcTXZz0m7bLHA72svKnZLtfTXaBu5eP0xSTwlfj0re9W6AxfXlhRItzr4xOphZkOK/7jMmSWw73XXu2/UrOktFzKWoYQAYF3LhH6l3dNLbrJfibcFq8sbvR9axgmXoV982mad1xnUdFglO3HeAIPqxWjtlDN7hxayLkXgbTHxAIM7USFQD5MkiRvsu1SHwBsACJbm8h3YfAACWfaWuI0oT9SBLjBbuK3EwJxMTQ/X/xpE3tmr+aHxTO+LLNGvTX5Rlq4ttNtpcaMeHZuecddAOluZSI1mddoDNpWFTNZeD9LdFuwsDjGTJYKBgUfZS1h4fLBZjwxFDsbsn9I1uDN8C5U0bsPTcoeogH6xAWphsR3L+u3ul26nNRetCsPtmVsE3FI8VWy2lpoHM0EnbuDbqdAzweyag78qf9V9Pr/9MKZzORz5zWk2ZrxdjzaKJfrfLeRnWUtILUxgKiRFyqSbMXqyuizmShoeSbzMXOFiHv7EQlWcc7UXWyhVUIA8UtZxCoreRyjJPdOmYbDzNsXmYJHI3C/7THeuIeU97FoKfjMJUgiQQ8aRV7ljayefjx/2ygPijC8sX2RkKYwZ/zRhvHs+hy5mHzr4/V2/YzAcDfS3ySjYZSVYiFXBblK7JcbLmPTb6cDaU+9rcAFIDZfwQcl8Z6t9OE1V/shwU2+qh8Ct1kW9CGi1h8HKFuS2TiHc3LsUwMPEuwHd0BXal4QpRHTb+/FV+MBXSrNUUBqF8RM13uYOe4m6+Jvt/m2NMTAOGCRhmO/8IhCLhbznlcD5qLb4ukTgyKaeNkmiy2rRx3ABjvSuPg52xCdXqyaFMS8jwVt6sKQ1naR67380ejRb4IlwOooBVx/SbwAXRgqV+DRlSAscm69HFecy/TEAHsnfOtOv6wlNd2wZMIQ2qbXtrzj5Tg9IhUIx6cIEoZO/QtUEEpXM7YIQDAF/HoZ/S6yn4EildsCL3F3kMiAAApUa1U3gzVE+9ikif02DipWs3CwRlvyQMolDJgzps9qcgJEWco8gK2c4PuXuMQU+lm9JX/GvK4CHxiWkKx3JzjTZzma+zfQ6zeVdnt+xq8BCwumCOfyh8BxHJ5OqIWIjcG9YSTsYbh4vzz88TeCsVk/wkOnduzet0ljeFx3Ms7i34H8RRP95N4fJ5wzvSsvV3lH/ncNSDG9KVPja0zG51woIvQ896BF61A6jq+lKJFUx7Ma6OA74+dyzogdETLLQDBKDWEALN2151EKT+PlqLgohM/Q7NeHg4bmOPwGknR2OtDryM3bbSzA9RECAw6/y3AZs2mEPUAoC9hLAChwLsjqs52RaolY7c2qDI/Qu39WbGDAXlQhH7HxWKajUe50+UY9ZZAAlG5fvY8PZKLZf32Ex6b699QHtB/zWy6y+ZVD/PYNIk0CLJNhNG0pSrX+x3awuYQvfal4uhoKliFP/9w6UdFyG33995249ydjNhzZdikNfF2IXlxDFJ6hkGW1nQBQ8Jupm+6hZKlfY9SrOWgMYHAWA/T+1UZDLsrz6pf76aNxYgQ1KC/zfg2u1NUXSVO7GlHrlwDHb5nYTat6LMwiHr9V7jgEUz53cXWUL3xnIt52+fBtZ/xsQM5QtfiIVhByQ3DtgsZbZQ+seTTlAVC1Ek43dnw1g69ENuf9gAm1TmsERb2CNc7oPHg5QPZwSiOsytORPqfEQdfcikeV+TTtXDxona/OOMKrZIvSzSH7PzgpHgTn3sanPsi/CHGhtk+Af/iL2D4wQhS/oHo92A4lYfWc8En0EbJ24REl5hAGsH0T2Xq3iIdHoMeZ1aQDkPeU2ZYx+duzGNzGx3S9fSLwLpN0EEF6VVCeF3cnt0BpzI7368wvmoyU/ERKUCHGZCt8Sz5i+KwVvdSbwmNNXKojsUNdzoakhIQxcKEN279WkOuXAT9GDzrhx0MYFDaf0TeRaCqz8joprD/BFRgZV8QxxRCS9EuoOLjfSMOq9m6qXUTbBSvAOOinQjRiEsEWfSaXAJgOm/mEB6ewtCa/0MMkFlLjrRPVmbIOwICrIpJNQHIGDIItIeUIxnxamWhnuwku3P6Yh0DwjOt9igHBqrtBuMeGKrqDj5fUvq1XxshKvlqw/mKDVFz/A3HL+WlXk5XuLyLkWgDKf/10zp1w81SspnL/LclqrE4bdi5CeTTJ9NYB4s571LFi71O4h2HdjJB4PQ93brzvIC0eUooPURfnO4PjPLWFEl56AoEOUDGwUo5ktVLrI3YbA/AGqK04gbzF9wEZEExIi5aJ+uz0fSQf10JusZj5+KC2MiVWjWzL5XHG4cJQBDTmPFgvLfPk4riIzHunVNQtyuft3X6JPW8CUnpzZOhzDyzFpuTuzHhkitutoG8Re7nYU/UTBpykyMQpFVsAggfw3s1f3CuyxnpcpW/7uwhAGgTVgK00HFQub4RXfhxxxeuk1RC+zwiTDy0rhT1RwtBtq8/Gfg3SD/MyiLzHjJrADFPcCE5VkR3rurVPvPGFucfo0nKMuRa4s6uw6cpBNVGR0W5Y0UkMwt3D+6o+aasmTG3Y/eG/K4WQCPQ4hmNuCNA/ppEGshEIP51bJe11DvDVH5hrwPJiGlRTxt4VNSmw+nxCDT97AOMis7qGdsIdtUE0jjumMdy25hZC4LvgsMxK7ZoJYU7+d+A4Ch/W2BIzto0G0VCBJaLKh/AqStxHRjyL7y8huloDiF4uwY33F+dNH6S7RGwabXUqdlJKhRGjl2DVD8iPU0ehc/lzfHa4pUAKs/I6pvHu7/ak9vuqwI84YN+wajvBU6VKQ32Q6+e/sQZZSAX9VUS3MFEFL4oQMQVv/rrh6ovp/T1xjjfq4xLPda5j+BqqNB3FkbNGlIegRoOYK7dpxAGYqvzSoplEm8YfV7gnOGSQZo4krQ1G2ezxjh4cFmATYVZ2BKPA/sz8Arn16gRst0MgBsrt+i2RVXOwE/hsHipeui07KD5DAUD0nULzPk4WM5OYpr0bcggrrTlp9Nvp7wWY3N/pPTcgLCHuDGerd5aWvHXDgh9cg0AkWgEOG1Feup+Icaiw+O3WIoJRbKyB7Ex0gx2twv/b5rq6oIFmRvtlLogjHYGIvPLwpsR+iDsopP+mo9u5P+JIt6XDLBYGfj6iFoso8MAOuc4An4DhCrouxHZwe3KPZs73498hdP2/OmpK8yituox7saJw9vmf6QswBoG4yOeOSryAF1EMv25OeXEXaw5mfFDr4oTUx3HViJqQd1RLb+r3owpclj3BU76F9kW9eNfwuhfcniGEyRg9X32l63CrFlyAtIEMwY+gWb83zYwOPR4mwJHj85TGpZYYSoVWcSVKRtKxLXasFUgyuMxVRU7FJH0pyhdPFHZD0irn5Y7dPIgmAjIQImfCQHS085KXPK0V3toKyQmhGdwQnK57Zi3hOY/FrF3p2og9yKr2l+YCwmR7J8B2dVsAhGd/H8ss02eC2vO0e7Hlb/oQaXZTsBm9OTO0ykVmnPDYQDVwqkcFhqCuDgNSr/incct5wT5azEwjOsISOadoCQloyt9IIgtwEPztAE7MX9XC82PxoQOCZQbqbs7d/xlFea2FYLJ7qilbHS1l3y8n11txhemyc48SOONFeR/prlMvgnoFfMp9O2EX+zhr+WvisrHTWhoJu+CRExHdwt2HjzStyiEYQE+80WekZgN5BeiNuuAQ70VSKI6gQnz+ZAkETEtJ3NXHR9lC0NxpQ2v+KcKkuTngKNk2ysgcEduPlTaLra+8TS1LL+nE21CuJfD5wEXLKt71CyZhTI67PPLMfk97fc7KYhvNdmIESIBLwRFZ/tw8PJ56CNMxQdyrF8JEJhrr5iXLIDrCDY8k4fkNRopz9LCqtB2c6tueuJy+rwXNmkJ+DAASRWyCYPFT/IzBAI2JzoIk6YKYMQS/FBWoYoeefL+DOUTHAKdaWV16sJCmGh3/Y8cZ2Bz+47PD+gQtTe7Z7UC1O5GYl+xlDYFHwTlMycFuQdINCWWuOedkEEgHeDkPziRrQImyOIB5QSUYbqDguVbCmrX/M7FFwOxuDxe3AgafJbSQEtxLJwIADi7dqWeHeAv/19DTOkWJ5d8WMfhMdEdrzZSmrBxBwnCE23rsU5sXNwJHdj8d6rVWzH6yOzr9y12sxWd31HFaZ+rAjnwZbybaSYiWIJbZ+UOVT/j+csbR93Z8eQie79tRQ50Lx7LupoAMZ0fGCj68yivcK6iZvDJr0kZysi99OWezGnaEb/7mXv0njJc1jOPUv1CFeAd4meA1YTRKOV/8TcancogAL0B1HmC3zz7rRaOFMY/+e7JF9xZpPuYxAWfZQJAU/sNhr01+HlC35R2MkJKl9+V/h8PyngZhMjPELujGH3QSIkT84YuV0x8BD53m/WQAdGAiTobzdsCJTUVcg8qiizSblVmrXB/2bNVN/ehjP4t5pJ1jcYrt19BlxdrHvnpDbNafxGmqE2L/i7RprD2qbdZxtPUZgHV65uSLMXs6xNqCNxQBEJNtL0+i+AWtIYa8ZL1abPagS8Zts3rfQGpC7JaWqMXU4LZPoH/0Rl20iGqlF0pwP05U3qZ7QlNJv8ANPTPFnNiCQ9f7ffkcSadBnfwbJX7qNUcgveIFuSco9Qc46/HqmaXdL4DxdVQw+m5J8osQbgI3KgvH0tBF34OgdYRFqx5inu5848lasIUSCrYAuyjXRxKRrfUouax26IvL2goCY8QOq4FQX18itRVPoS2Cv5NVWNqi/3W5LQXpf5uFXNHoPCamdrxBueF0piInLw9EkuwDBD7JFnnmJhodGXJ2tRSOKI9ezeaWxZjPM3GTxW82pNVHXQla6H5kLgdAdSbNLUyh6lHVHVOmon3Mou0gFjDH5q/GwmsTtxuwEt36eX4CDdiK2iT6yexBeBYX3AOSsgGwAYgAsAIAFOYvfdQQmUquyFKLfvy4XgprvTvXD99zxvcKgrDnk7qzvA8dfyHLDSc+TS32XWMrFsdn/T5WlgH5NvUmuUikIvIC1XbwZ9pMkIg19UxS3aqYnpihbsMPBd2jr+CgbjiumneYKoOTNJ+5g0A/8PmVz5Q+CJpBeCWnom2xj6zakWy4mnHWARBFfgqEhs6t1ITRyz+HvqOoLCl1S7nzs53wQp6YR/L1onThPZpc5KWGx9qHtV2triXrNg6F4UR5W6ydgPpc7ABR3Fh0ZE/6pojYyMqAOo4NND+LHbuBOXZQvVa5fJRlW0zNMPHVo/Ho1r4p7aPODMnmnhdFc12ciZ66x1HoLaHHBIPKb52KbEAOTN2wq7r0hpTLr6kFUwh6zUH4C99rIKLZaJGsX7j9MSerD5Kclymj31iBGTxGGKc3xHEHbmq+yIAgdPWn/iLJAU55nG1T+jk0ENXZD0tzrZEM4jiHOpOzv7sycZhFXO+xBEY1YEPaS+jve1of6IeDOLhA173m/GK0jEIc3TbVu+xigwXvt13Ddo5qX1iP4ephZvRRqmJ42kZBTBAm2+XCBaOuIfFKNrysNhAvKs3DWbJRH5q6lj/DrZKQYGqWaPsoaZo49kXCRfEsiZS5S6bR4Lei9DwecOKQ9wp3+ADPuMXjyaHTiw4UKhl0ufTtWTOMAAsmUD6lVAJAkvvxAZd9k/I1dbhpi1YPJOGZhwZWSSgDjwfkoEP72T4mnQhwxX3vTqJ9tB9EQDjBqzoTfOi08cGqdmW4XtnJZKiSGmwLo1UFLcbWBv3i2TVU55xHwkJNX0uNvwsFMEGTWjkCJB8tJimgTGPHuHHc6gZ5J1NU9OzdceQL6gNykgNYnwbQULmpvthaz2AsBLe+DT2K3S9HN/7hnxGpJRGDknQ8JgazqFWuiB9uxq5DKjb/t8mzMUQE3VoMkGtcXMnkwEPK/M/p6SpixQcUehvv5IDUfYagac8Tl+2PpF5lqc0Nt1HECl7SKEyjwlF2ZyAzlunSUDx0kzVMbARHzaOthgi22OP4ZQ9jZm41VLylR99JSCyoS6Jt9EtcBLXDN2NsEKvz9CT2F4PesLVAPl2zfZMOz6+HAsxLNlTrH7oHmZSa+sJNaOqLzaWY+G5OuiS/vOwr232A4DBmJcULTQFG6MM2uFaDdn/1tK0sv9606mDGVWn6uUIofn+cuCP7WUEEcsCN/ILJlIieg/ui4EeSc9wRjJXNDb7j4JbYaIkoS4xQDl/5UwrAbyeqALcqSHUPkDSajoJ5Nxm/Ck1rXJG0i7G1uzS+Rvt27L6ZmpSu/oQspcBsf+uIPPamwWn7Z5BJayIJ/C/9PiZ9BuNKzbEHmbsBO22L91NZUyLcaf/g0+ilHgvhs8UKgmqr5JZ8n2Z+vTbVrbV7uKQCGIwtIrbAQJJdluH07A1I6qar4Cgfscx9oycmUdGHevtMJQbG5l1nZc1AVqFDfdyQpvVR/HerP+UAjD7TcUpG3vtKoQHPGGQITyXwxtWAu9gVxUhQ/BzwoySadxboUNcgFLMv7p8phG6JWmKEMilM3gde+HKrNdbZfOnD7zrnXQmFiz/jqXTrmsKb3QRH7tNc2aRsjUqZa0bG9Ia/Bd0rHcHJ8wlJMPy0GSsYL/a7P+zcSioyCE840sY0/jew/IK59zznYknDxwAzLSDwCLsJdiluuLH7F0mI4e5WD99F29bn4sx/O8iJzo2LgJIfCxHsTwENJ1DEjNzA7sXGABy97q5r+faCmQcTuw2kni6yw8M6jKn0yTosgJM8mlyTE7aHUoM1LmLv+czAgZoZhRW7BNmSeWut/JdF0+870dX+AfAAkreTMp21TiI422ihuQm/p386JqhpzGtPH65enpBKtjOUYX2oYsp13FeX6Ci2syDuDlDFSZxH1dKICLMnhPjbntkyFNoBh8RPtRhFMq7ZTuD1DJgqLNgxG/jaFUTpQYVB3T8lKAuexdhGREAGddtHPBawgroN6xF84T+DARvVaWlbfKqZdHf8tAOlwxhDouyzDfkp6exNinyT6Z9ilxE0Kv00+KrI3XVQd7JnfMQ08biO7s1L35VXhu8xb8/ysKBIkGyF/4gEQfwhB3n1Kky+jZKuyWJA/COHVK+28ZG/aHSXoNkN6SpuE0lrFllV2ey2OxFIhdYGCZwkrUrGtmd6u1qalGf94j4Qhd9rye9ZDrV9dgX7CbbTqmIXIMiATKqmXThuUGdiMkaVzviAGwGf9Hz5VFdOq4URYcJfQE8wZJ4gQDnmqld66rQpseW0DRKHqZn2tbw+JeIs8hRr16k4098ZaK+wyF1KtJvqQBycSwai/eCFyjzN92bpxG4lD3dnlzWaNzSvB06Ho8dAI00Kig6knLtHEC/D2J2x3HA1uYafoPH/gurzlps8kQX74z5QycZbcwlZSTAMBzlasYXpRg+BybtmR6aNGvs4Ip0yRZVOS10upnyVosc3SGX87xNYJfxkhMN900aVoyQmQSKrLxm00wc411ePY2L3XUrL60Qs+njLQEBsDlYL82RBX+Z83F1ahuCMpl4HsQuY0Gm6M18BcjvwS9qx2TH6AyYwHvzH0KKDAQ9R9/WfF8RzXrAN6dtIMXzTLFXyvq6q2Z0wkcCK54OZgl0+bUjS3gYqzETJklSxBG2EWRJzagelvpwEdmgCqTldS9QOxnFBhidTfsEepNVj4gbiMcITUn81nXmf+5z/2qUrIO26q5J2+mUDlDjFKbkxQ3KUItJ/IACg3YFwL1AU9Kf8tnDjlphBL+7iA/2s2UiJ8/i2h3G+pvfzEx3rCn/B++gnNn9ZIwarSjK0om2e/Tvq/1Xv07W+3kNGNdKvYjqnY+mUvLNTH2dg6MyujfGNqBwNjZQnGiV0jLigmLuY9ncX6YkmZEkO7MCIP1vEzZksNbr4etGYqq99hB6S1CLLo0sKeAfJ1qRRj2OG2A1DqiaPsCSjDEqHtPR2F2mrLv3sPXV5K3JmhRL97+97FAaq97UzCcuJiGuAuNXpt8sC+WZvC7Vekf3zciTeTa19bg5gewiLg4KvKIGGSZ5CLrBXNwQ3jVicjCvw+/LJzloRgCaQk7kOH/PA6QM6RzDT3meLfSDySQfrlNj+7QheOZSejojqPFswhE89OMQg3rmkWrgkWcTgaTHhp2TROwTlBQqnn79nFh5SODFSfBpKwZ1zOgmRF4Wh5w3jm7mF42D3tFIrBZPGweOa9EY0EN4hN3eduy0GfEoZVH2/Gp4RUK3irwOo7sSJFkGvgIElHj5lXK6YPFC6M7fz0OCGdOg2HhZJRlYv2jTvW06xTUQyTRIGxSrSin8vTuaKvgD67pywmOgXogwB8kuevIdlrgNuznhaA/ve8LctouMhChCWAimjEt7FjdmrRMX4uMeqBLvaJ8E9xOvkwjFv2VqIsTyzPodK9poFqmrFpPUjNF9yGINoFDxUdiqESm/lks8nlbB35sCZqumYNUY0QwlnkuhNZGwwjoyn5+8+WooXpPD3l4K8Cy+ScJt01Cs6yIBlGyV0JEtM4wxwBkUp/YEVgT4W8xG9IOALnIT7UeN5krb0ma9ItS7YLkruT/CfrO5zPlrUr3WMBzZhuz71hjK65pq0k0wZSO2x2ioR0Bb10EOA94AaDS6DFUXszL1BdO4S/QBaIwzubfawwBlZiZMDNwe1A/MumAOgzv4rjgCeOIpumN3X/He9wyPBEuqVGmCZ4KqvUC/ScSQvn0ZIrTCzyF+t6oLrjpazb1xSMpCQj4vYF2g8qkTE7jxuQbJejROAgK1AzXRse8X9MTF4MMjcpXZ68jWCEuU19GUFvTNGdYP7tOjF4Gu+lXrHA0xLcoDdMFCA0BlkaHoFBf+QKXipH1YLvSgZQ/ML6lf3IoB6CpXWgq51DpulOqpVaabJRzKlxHv+OYBWsUsdRRxnM2kS0WjzXkVdHOudvGmPAo8qnoLJ1uWIiijByR1TdNbCDVFF+fB8mr1SG2JOFLKGVa7Hty4VZXHQ0ZPkzyJSA4lE5hQlcgHdwei4my4I7xoResEQgHovqbUJm/3I+rzB08nAGafu8xw/G3HJc7QEoRDfcBj2ReJsf558EfzCEYyJoVX51lXrSqwRnD1o2lw3NKzO6AcrJEgDZ6EApDYJVQ+JDHOezP7Ggm93067PyCuwfBeJX7FJwCzM7CJMOpQABYbS4ReRgKAIs7sr+rwtwUVCpRHxvGyTIiu8GvaUL1dr2Wn1/9d0gyCqRGHR8lLc9V+wQBnK/FmyCCjpWY41h4Q/7bruCQm7gEFep0QtwjcrkbhnqMA4okZtw3u8rGUw+vvRcKraOil3EajJkucRQhnAKkxG974TVhLeEXKlb9eDwsZEFhHTjIzxPf28E44SsDFxF0vSUHbZ9UFLussYh8Xt94YMAIJB2Jwtra665UE17tVYr25iq4AMfhkLPKKW3jIwrV/e8mvNXN/knurWgFQer6enVrPFhUDr3MPInHfwKdwK/ZaBnu/zyetMv8uNubUe0flndMLJ7oXDuSfjj9sE72O1a/P/HcG5ReZPPsE0CZ8iObTAiBy2Qb0boPPKceT0A7ZnB0n/qA4LnAS2GuooCxyyte5uT2Oc6JAbib3H8V0PWjiexI7qbMvKPMkTnU99FvqNU7T+6l06/r5VAQnKasIq+BNspERfIMIzN3OAbIU9nMbEs7objqhldW1ipY3Jlo5DHo7ig78R5eB/LseD7RNOGhuxRm0WbqybTL+9MprLPmwmgIOh1lGBwZ3vrdf89o6WppbexOsYUNakuQ6jgv7hbQOS1Cn379oekydntnydLdd3wIjLm73h9gPGFF1J6Q5U8ZWyCEYFj81jg/9L6e5XwZD+gn9MdfbxjeOS32lgQMNnD1WtwQUmKyJiGEExz+GW0feHT/dIdiIkIICVkoky41DEklA3is0cMc5bJnX2FkFJEwUWQ/TGI/oyQD7HnMvKCYP1cTdrpYGcVNZBWE6u4kCVteM0q0DyTWJOfeeaOOqXV0P/JTW6rGRyFa0RjXDuUe15cbs5zGs/KpwlD5kKMHBNA8p5jyuBr24aCcxzJmUhYsCPdlZQ084UBpspbUGOwQKmNH6E9ijBQ4k0GD9yU/E+VIrkfmlFkBOdY030piXVeZdTINwNOQOkcRPn58HKRTaCaqEp8iiMOXFD0xPqXKpzyQOFIAtAc+F2lucD3W8t9Ag22UZPgj9B87F94NWnE8tp2zn0hlz4qvS804llnE4v2NZ8qI41ByXM/djsLew103MC0RZ95lI/0Zp2cwy3BlXvhv8Zo/9NmU4lLN5v3Mj/797R8c2WDUwL/wkgPd5KjhjAMqlXWbj+jGpFq7LdKwyLHsgaH56/3GuLQukE94XLrueoiMAZL9VAxlvVMV+P2meBcm6Ee/Vzijg3IEPi/lawR+nufj/LwPM7ojJzfZp4XAEWC2L2etCGjePeg6q+Dpzzwssk0Io9aBpF9AACVIkpSOoUlrxNmt5btKF0DQyhGaDmie9XQZOFrmavFtxkvvKEsIoGJkn6aKRfecjHYwioQZyrzznJ77SuAyfbkkbgZWWxafyq5D/VPibvLNCBTl7OwG9LKes16WKytJm/jTiV2clUmfflk3MnCZT+oMJUEJExuURNnayq/vnjxf183a45Enrl+YaGBGKLGIdSZEGLttOimh34JctZlSdwmAGg8IVcHFCDhfosKH4IYqJvf/oO7N91YwtLnx8qjYAsycm5GOIWwiy/bPJwTR63DbI09aTYG27C0aDceMyDVsnTCswwI/Moy0xbnaq1u66YPQpn/Ye5XY5Gr9Fa9Hk9zCoPPMYTOc7apzOjKRSE4xnSe4b+EkBTWoL6BUk3AM/0ODc40b1bvGJI9QP8eAUCOZCi4qiuvujLbmr7lFpJT2/Jr7hN/PylBjmMrIXWI7iLyNVOhMssT0t6306uD6PDGioGajAxbbL/oZgDptib+FNo94HKgE0Pu90mRF2FmYg9Qo+31Jc9yqM6zLt8Yv4/eOO2aDJDN8HzF3+ZkNF71Os0mdVXBV6XRacI9aCNuJoRGfLx1VHgzjve+LPNNqTeqW4UjA1ZMe1WSoYgOBF2532kXeLBpGhAVrtvLBzrp78zryo66C9ptv014EY5vhXPTr3Is0ubiUkZTlaO155vvdCnxjJ0GoEKn8q/iNZSvAXTFISyOuyVbqBWGu18FcBdnGJlS91ljG7DPSuoc9eRmKwQOwZJUay4XNXhiKEHRS18PqnlSp3es3OquXSlPcXaWekvgKZb/4gNnI0kVv2ZMm8rFTsSkBoeLOiJU1przBjNJoy3rYcq7ITx0WdcU/l9rJZYTfwwT0cqaP9KvpPYD10ESEWnH5NEwD8iGLl6FN8fe6zWVZmwWakMLt0IDN1q3brbPKERbhsS/HIG/yV35u1B/7oVGrjLq7fOw78wxYbUB24iNrvfIODVllNfKZUuFEvVYUiHNDgIG9N1BFmBvLZJu+kwSodK16Hu/vLX/3ksexDalnqEgSZ+WycrHwqP7KmWkopiqtMY2XVddhGgorfAEcodOnVfOZWjdGbLwUG4sbLv7HVAP6f//TOC00s1+kXw70cOxOElYLu3lnOznVw5rftZmqIs44EEuX/UrFM9v8xBOElIc8RKr7jjHTMeQD6u1xj3uHOicZ7oZUoGd0dZD8eBkrMEkWxUqrG9he2zYuU71oj3uUqHvyiws6h6gj1PAhbMvIy3IAyAakce51/iBDTz9NQsiKSBgDK2sjFdpYzeNh1DHo8/u6h3q62MGpNn4gub8KR9Z3w3pGiHmZMAALPd1six7t9JVQDLI7qnHDuN+QwHhzlIUwMTACFAPxDkli7n4fPRcgeu1J/I1iFgBBYRRc1sS6eBLRWY+ljUAy5K4KWp8zGJGP0A28fwL6StZSbxOabzpgYG8AgAPEgrPtICbnHzs913bvnp1zUKJ8kfOjbCy8oqnTdpDywXroiLL7O8V4iXXOKOWdZVLUZTxzt9GHJmq43P8H7yBe7WchLxS0+UfxCBHMZ5JUmjFrPcIfK90LhiYtdPElI8TfgxRxZaNtSvwzjtH+EP7408vrMCQc0SOJ8/zcDoeTyns9S5TLL8rruFcOxSVf0kCQNb00RCNpgGEDoeAE2jdHQTiJbo4N1Ald2XTr56jZPLcQ6qXFSebOe5mQiv0Uby/uL32vfIIgZ/x8o86m9LJpYzJ4RKsehAupvzIN3XsHSG4v9d7vYg3WNioACsRMsvLEaBgD0/SsIceNMijWDf3fCQ4Dfzb9lV7+t8+zqAKf9SSITDzfMQl8PHM3U8q2PdYvcPCoyqzqqCfn6kSiLGhgCHQvMV4cAze6njhWJQkBAW/aOtBbE0F0FQDc7zC4fOUsUNrF9z1JIdBgsgEsEt7OQgWcIEdn1mloEluZvHm5RftYD+lqfMxjirP7mwkP63kYh9wZDlpxCsgCeENxjXv6ugl4f4h6QjDBTdyr7f72r4K7XIllObirzhcMLsbztnADsn1zFEnVQ2sfJigk8gOmA+JekyxSCt/oBJr1n//xV/Nc7/AUBDKyufA5WrITgFz1AlgllZomCdXpODcmZPhdjnh4iOzH/9nGuBpgsrX4QEC2n6f/XrSofO7unJULciQwuLoNzyhY9vDgsa+oLBJ9p5GTa8N348zmri46cRGC9OirJMM64DteDpTheSG7gPo5gQaRMCngb+tTdehzCmtSuMzkdgbaXaO4jcgEkZbQMCVkVkODUO8u3SHmnt80reZQmA4ox3V3qcTiiIWnENjkMDppDIxY9Fza6/nZsTm+o7ksxKCHa9xRpxHta0PL3n0b/NCQ4XDsWGlFZqPYxiNx9KL0e7CMFqb2dCPKCKt9gZ873QiSfBsZjhoV0DFVm4eXHUIhfcWERmt4rb3ecgwHwV488wekj4fPsilBXOwhAKVM1rB30RE9+61Rs9ylcIPg948cLMFDvrBnjPtv40TvPlb11R7rEjLFVTiUTSMosferJjak2mzrfFZm6hKTouPDUS7+zeqQsx6WB/KukE2+N2faQHhhnwvGNTcDoJjp879MkdPIB+paYE9aD39BWICsHFTg3252uYzwAJ0SBoO9j29A0EDvLmYNuEredGyKqFGRsknj3wzzVeI01+30p5oDurh+7wshHb6mWqF+PSq8APk8AYEgoUxP4HXcaS+LntYTGwuEdqCT2qLdHPKU3yM89bF7YkE0K69WT3FYdFMk3sGhVMMJyx/CMj2i7kjLVkafNrPtZv0HopbhafPQHSyqh0PwRzYBMlXHGtbbTBKaipDab1Eb6+rpsDmGCUhXa5Yw09sS90cWMP0M8tfa+p0MCGOgPeAKfsEojw5ld9kBxzXVxr6zv9M5PGYyoGHG14v7empPyDh9y5/Rj4n/BMaTMnF0/acW8mkGXNGye6RQ9BGAKZUrmZost6V49GFXVRK3QKNgSxe+6p97jnQeJtzvWBtrvw7hZD/Q7ZnYF64YlJsTHLC3VQ7oMbGEilO3ysGSIxkgs2EEjvzeDayidmfebdOxuNK21ZWb/MI+jFAi3HSeRb+ylJnpeU5ZC7k744mXWOfHWbm2UNy5GAv2ljw3zjFwV0Qk2RQBA/DTnGrqGUjY+vSm5/WSVzTDiBpBIZdXbrrsF4KqUgUCXxPREBC2xavh7fYGPZuNxyns6sZPshQTJmDV6Eu/3smfsGybWhKpwTh/0E5yhV5rX+PwgodDsZkujMA51V8AceP9HZEJHo+onN7Mf/fFCIwrXXVm8RmOZq2XLXZsNc6dageT39rVzPi9v+y4ixS9N8S7G3TmXkpIV4/2NF+DMyoHsbpzW0pJ+hOsNQQZqpowP2YFNf5HMwioR4MaDN0hDLNjmSYQ/mkcfOhG+DxiD7Aq5/H5x8Mji7ZodXVK2nsnf6nSZqRSBxUnyiiWpehYoeMLBbtivQQECdcrlPvNbt9YTi2HTQqyELPP9O2HuXB/zq+wEIuAsOgb8AnycUR/EUozw4cTyquKy4LN9k5n73F2wm0KC+A6tNP5JHQDeHqsXIFO11Ptsi8om5kZem0rqDb5c+wlGnd/XN0lQIwQ33BLG8Yco8PO3dpT3PKyA9hw7EwUJoz2/RDB8HiH64xybeQc0LKmCr3ThcodZmmuthC1sFMqKQiKEfX2Wmu0fv930ZPH3FDjpJla8V2Kz1A5Od0aQpIDlboqpAoAIXRqDh+D9TDo6CXxnqsePOEcRtm+hAkJ2UuuV7+JuA6yt0bDUdS3zaZXnQ5vzWY/H5AUyi1qUNPRuUV5s89WrdUMIm/yTdcQ3PMUlDmedYS5ufbmeVPljwWM/wj1K+C5wqOYH+xGSx9KiUJIImxbXNzbIPWYxurGPMPXcV3PFhUI1ynxx4qPGBg4ONxk+s+sBz/jsM9IMF02tLg8+vwcNsgonQQ+C971F8QIgL0sgPDDRXubeYupc6I0ahSX7IQAtPCAD6vpOIk/Y/h23EqUD2p9LYy21nCQrvarnLESsBfLB/EuqqBxeooLJsnfyLZfynMbls2Hzm91bJxOnlNCngVAZ+iYtGblAgtTQKwoZKRGqqIJNC/fn4FPQycMM9EJ+MqZH5kgM5RY7PGVrSyVkb4Ux+nrHCMEtkrE7advNb84k7Zv/KrQF7e5C3G8TMsjbvSZIcKH91WYDoPO+WU26imjoAj0j5BLPo2M5C1BRPhkErlkOpPlSnK/OtEtNamcCHwUVGXl8JeMpu0gBfgrqyjxsWC5WhQaDip6+59/iAsGXU7+j++seVaSDPhsK0Qd2519/Pld17YCOLxozuBmpqFN5SuVxFwD60CVkAwsBv0UPC6D9wXjD48Mf4dMBgTiieIiGI8RTLQwDsH2o2jOx1+u6C8LmG2YJ73WpcsseJiN1f1K/LG4xeV+GRjol+xh4/8KOOlF1/OBMVFnMexZNzCK02jKwTRf8e2NPC3d+PXBPCTXxBd2qKsHOHp/CXcZ8AXhCKi0KZeIgHFXAuMjz363YPITCwUyMgVG/ZrAji9KO9wXlmxRKPRDzF+LhcnLAndxOGk3il5MCq3lkNoORWuP0yfGQ3HjLcIGzb0nn7CRqsLTDUoCCS0woVG8Gi5hnxgCAWgIPJqX5S0iUD3RLwpppKrnDVRQdB/E8YPuUuRE6SyZrHQtZBQjAoMyJCfZCgrPIbO1IoxfzN3qHNz7bG3lhZurmzzxonwBsxDv3sMAzTTvY1hClzZTojbTqx2V2y9oq2CMiPfDeAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<PIL.Image.Image image mode=RGB size=64x64 at 0x7FC1D11D29B0>"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from torchvision import transforms\n",
    "import torch as t\n",
    "to_pil = transforms.ToPILImage()\n",
    "to_pil(t.randn(3, 64, 64))       #随机噪声"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAwS0lEQVR4nAFAML/PALhxAUUWESfgoOT3l0GWQ7JxoQ31sJjh8tD9hxfq+6vUHEWQFdd5xxzow1l8x9iOlZ/K+CdLVrgeRzHlxvlzOjVp082g28V9pbWTHuy6Scisnn+wJy7K6keQ3EPR1gDFWqkeuZdvlCQB+AvRy9RZ7QaYMBYmCS90deFEjJ3vZOB+ew938P79WKPDO5GAtK28W/5GSxjkadpHdieFHJqiXp12rV8n6OGhFRr3wR7+X0w8oC8yUXFjIdLrel73IQBulwIsawGRqT33W7rkb1schAG00TtFQZo75AC2uSGjKrpgLbcP4M3I7SDFgz/6y8GQIiUV+FhWehOZa7bcXeiiReumDGdC5KUQEcL+HSvAEARmKt9jK9J4hpJTEb792IJmaybIT4d4NkvfGTrO8ln63V6Gm/+wwmmzz55YDvsNL5Narj2KEEMSVKQjEuiDyQdAjQ64+MiSBOrr2YoZ0aZX35tR+eT3PKcY1eabfl4fB1zm2e5HiQSgd2tm6pJDMmEip70B0g3VhoEzT85jLdtoLv8VtycuwaTbehJ6J3WUBZG7WPTAwY76DIe/3U7IpELqYzrCDKJcoG360mW23eVOB7uqGy6f1LwJ1a0GXZe6ZDwyXNuX2iWvCQvt407aXUjEPC460hKfcIUkw9pE55olgdxIRaN+XZ7vaAO56k4+R4r1EmiQgIemw18+9ZinDCdAWowZJR4foohCQSb+GhFSbdsU9U4hIal89u4HokYXJ+Agnqdh6Tg6ebzWXwOUCagElMr0AZBM/+7fcvCDRx2lWSM5eyIzbR/UfMpN+VP5qyKJtSferM+tucmaPhSLBAEdNfAbTHHlHatGk1PIjgMHywIKo8NK+fLMR2Q2Wnbf7IKnWdhsvtUeaZRpKdpp12rNGHdDLO3XHSCPk+kwon1oJ3JCCn9iGEm3itY5Ef0RMFeBrNWqmWDhd20EX2G3mQvLocckAwSLJXNGpdBl0ZYsS08ArEDVqr9MoeUfS/on+hnsxv+sG/wYH5OtcU2PF9IiCO5jxAJsiTXiCs0JxaTYisuYCRAFFlMTyo+xCUvvsXTKdbgbQTEIEE0CXrIGwHfK8Av4uioRTg05dM5Uf33TkyENGWHErT4diMka4lMUHvSuO6yNrDIS0/zMBKGNkrtbFiiTgusjSIctF49zSPTWhkddXmGaNPEQ2mq3YVgH3+T+49ZOMAzuyvaoI/3c8pt8Cn/rAMDXcH0/6WdEaWZKQV3Ydrvmq7p5PwA0WDNYO62L9KdztRhzE784u1GU9pDW/3nqqhIEF42mpQjsF9MgMPFPnojM/PbmH3pPImKvuiMVlDH9QbBIrY4AiXOq/xqemEVEjfxr8HXAvEflHxAzYCi+tvI/zb0KLZ/yBl7m3QsXIfQqLfFKlD47eyuVC6h09A4eu8mEiehpiDXSpwF5ptGDg8HxF1CBP1t7NVUmLH70tJfREAqIBOrKVwbA9oRf/iM5k2mr0AKPCtuGB+RVyrO0y0mJMrM/WmwnM/SDMqbEOfaNKG9da9AvPuXL0dJ5mXS2bQw3BN5+QBZlG10d+8HHPSMr/7eUQErLk59FGmfRqa2hcriQWsiw0xzXVeo8cK3k9JcKmaqIodf+c5k51bhqb0MNexDNfNYozRKVXaGSg3TqxRO2nk8D1CuniD1FLKsTpofRnJbU99PZgVgOSmHu/aTiS6z9FUqiA9zUaezkR74BjMe6jthKx56Ah7uZAdVhZj4RYckteGpUHu31IwQvfeBzszeBpyyyxt8IZdoRhiT7YZMBNfIr7rQamqqHH4lHbBtFtgJnWRsuhsAsgaCHpi0dopLYVowEJEWCCLiSaSh0hbWe/tYBlRr1IT1Djrnz2tvt5G5O+0UsLkE8/ufhTxRw2xQypv6a3+bmqIkGXc1MyDit85+o7BYuACTk/KbalevIUkjgrARf5WZ3lrlQjxhxfZx3qVk69pX3vWySyRwKJlDb24Jjx/jpfX3uUoOzVgQuvVuKYt7FD1E8rkQqYa3ggSsElw8OK7ycQkCmOKnEvwQ659hvnV9D+djb6zxsnTTuu/MESqovedcl8DN2k1U3TnLGyktt9bsQT+Ec3HOns1Z4+zTBIiSDsMHpOrJhr/EZ4OuJEvmNSffprKMT5Owqk2HqqfV9/CfIO7w/WqF3Ar8hpkNaeqBXsb5ZbAP23uVg6A2G7A0KUCtT23fNU2PKun27dK0H0BPl7Bf/eNzSGFnEr06V4RabYrG/dQfSPQoUQUd01n+83gfrQI8sCxlP3N6YxlJPx7Z9YR3HwWJuD1UOTuWElTMlZ0uWzmA3a2nFVhY1ARKs6p6kst5aMLVC3s+AL3AmR8KBs4hpk5QlsCqaf/kT7RdST7NL7Ai2RZO21lEusHdS3HdvFqSx4+yef+3ibtql62pYevb64JN6QJlUUVo3ZXfN9jFvO/z6H5RhFxZbpBV8+W8XGO/0iVYAGknib+7BPers4FGn+dtrmorbuzT6yt6cRNNUFAzmsdLisgA67/fyaJLyRlVeWAPxCQRO7igGwowbKe6g6igl96q83WaZ9Vg+fWACj9QvS8I6eU6jLwHW7m2JR0uvo+8m9wCCdfWnYbZNZgRfPRCBJXI7Q7q2CM7sgy7DScidpin2WxwUIlUDH5AiE4Um8OFVUtSDE4hnB4OCITPcS9cF4YP6NmJNQ99Hy+5tJtZ52ITJdvRDoLYDgG/dI/0w7oJRhgilHrlv9QAepQJ0kh8FVz9vJhzxGBxqreWNH8H7hGWPZ8Oq7pJ5cGPxyNhje/unSMHMKRNENjiO7n5kQZXt6rgv8Oa5qmccQ77xb90Cxhj70IZ2XIMB1DWqSLwCjIfoxXzVeCgrD+CVOY1qeznddzp9VAj4Fdj9pvXcHsztJrvaqzdxA+H0pZM8wiIW9VmIRVAmaOMhYA+8FypsILveR1K9VIgkf+FEl+hx6IVOjJp8meFt7udmsZ/KyAQnkOjMEm6cIm4EmiDaQ9Yw7zF1JRXM/iANfM9fbVIoTHaNOCob+llrgab3o90pAUKDIt5GyAQIlurz0mUfYpHBFA4zTWOiEfzkGP2QInCnokUbddDOL47jJccSAQVC0ItrY4r04lnoHdnyH8GESviwrKvFASbjM6EtTB0rQx6Lntj6OQY6ydH7IuRmgKfI5YD7giSwdhYSMgwDmHPDzGoQhrWc05so9UcE5ULdqWQUue4yV6ZtUnX9tyhHDgjxW/BsOj4BAhNw9j0Lh4GDPiKaFouX7d1p3zfFahj4v5pDHMEpBTer8D2rKlQyRC5C+h9flg885XwdoDZNf7QE0h5rgOnGNLIQp/U0MqHkQHSHZS5iNK/HeygD0fWDPQC4BBe1ls7orhxfx7NmbALsI56Y6RIgoOIr2Cv9Qoa3ZTwZYsMNdcAEaueo5HFA8dpuhOHSMdiWNusHbkOr3bQlWJ6TidG5gJZEAfTjmWT4w2/dHaeQWpkQsWEu6WzdZqL8yJpMOzgA/gfFFZzepi1swJEfm8i3MAShpcwNxde0638z69Tzz2N0Um5jPtNdaFgBZx7a6Q17yKS15InYBTxNCMrD382yXl3EW81/scFyR4QCV3WGLsZr2TrqBflUd/4AwmduFVcYafDJBF6VCDf8tn7ThqyAsfP/Nl1ASkaa2j5MKtjrKifp5LweOUrXr7N4wxLYjIg9cncfGRG2fYsVvjv9ZGpA6KJ1OMzUeC1+V4ng0bPhzy8YhfyYR29RfjkOif7jLs95wuXYtEbbWEI1S+okm5njJP5m14gLOvihOSUZ+DdwQ/eqkK/gRoc871/iiUr394Mwlve8xUaBFc/p0QpWDi+e4YacNSqdpmX+NV7Pbk1KB3XXRr/Z2ceotIvGBHkQUWrpSEGzpNj6ZLuMjdNq3Tv4/bsTrQQe6d9AERkHvT3h5c0P5sK1aW2Bd3fX8d+0wKN9kawtFvPOzjlUQQlc09sxkhCAHP+3EJEQG26fNMcEyvXLmmGzECDn2BoHQotGkh3yEu/u4C7/I6K7U6yWYAOlaNQUO/ybvvznoxpsHJpYkaZ+fcaf9Zx9QAI4Q9xmBy/NZ9/39pyo5j0BJmWR3YrRulCg9r6DloCzBxRCCexrA5N8ngetMotQw/wo5AHzzDMPCRVliBbPrviOQzXSNTXirom2XuLSozVXQHKiw8FglOUxtKsGsWeYKTNkdWpMqgwfyWKnlB9yLva/abo/FSdZDfoykKM/bF/dGwpq4bLDS8cNn9qwsUfZZEnOtBPfYqv55FFt3yrZC/dXjRLg8Eia2p9IR1p9Klch4wKYtDItjN2tldx0sBZW/gi52c6iKr5iVDPfpXJo28POUClInRZqk7w16ujFsuq2eInEVEo2TcfbmWZhevBRyzUgEXoBAUxhh0vv8mqa1tHJL9glK2x3ipMzEzmn4NoFVOCJLw+N7QbUFyAw9AZQHQpaWA3Xt/wXzK90vbkOcJXJ3RDM+b6SPjpTiBmdD8DS5HqNgz6/8azHkSmhBH3l5Dp+LJN3ssjfm+TazXMi40Y2Eb/DeMvvCnqbh0ItVV/2BuTdjWCJlxq67LgQpWYpSnpTgOyQymOjyZg1qKWhYwi3ryN2FkeGxylh3mf2gPgArxJJTQqasfTkWfxXWtRGrGlTCXTRAaSJXv1s0u99Ie9jMu0AJeji3Jy7F1DB3Dsqy46AGQ3v/S0FUuwYzTdTaG/X2v5W4cXeILtDRukLiz8L1jR1ElSNk4d43N2W596lNYNNORXwfn6NetZV3dIGCql5xiXeETzEP1QlgKzM3HEHGCFEINehwTRKwyrr/pTXrWeEAzLM1Wnz0UUisZTdICH9Xoi5st5n2Ajs40vVFKTrtBx4BZjP+Q/HLb4Jb+jPOc8d9DT8it5aZc3KdoyE6VI3Sq2KmgEdmOnjNnwAbIEm/MJRj55kRa9ycQnlEvN2bMuOEr4c8effvPncR+ORUDQ5khrkDJef781OeHr1Z92XTi0UgbmstHg7MXWe2jJw/h4jyn0Jnm361S4PaeXJqAOc7kXJx4WhoBUter7fUNLw/7oV0r+CZTTftHlSMmXeiVDSifbDn5gHoAsjxrwg+BDy9JeQbUfcwsOmlzjOWqVN/R2u7pJkAKMFOtMGa7vb4gGvoZGRJRJn2jHh1c1dfQwn4VunoqwAOuUZowu0clB6EI1k+IE0HynXWb2AbkH6fIrNB3mMaS7NDOghi2Ph8U8c5AT2Nrg73fkWJ72v6J6zu0WfcHXqG63g2k8xSxpF0OHwrgu3xuflVqX3osyghMTSuQtzzNmm6J8W6DY1vWOwUnNY25tFZpED2a3/CS5fSLsX7ojUFX/TWBnYm6i33DTvcJZ6z5dlRarAdilT1+gHPMfREwBHRQq5sRAKd97BBDmNrDXwIaCm0MawLQscqX7qQQuUCGFAABNy/BKZ0aPSFD3Df/VurE/oXrJJEPMxH03J8o6uRS07CRwOtL4gsC6dLbUL+O0ujrDLORAoCPqA91Y6ve0JMfwZ+QAhAcLNmmKRSlG2NJE4BCcAbYpif19z9P6CfBk7K1kDwokzLEvWa2UZPtl66NXNEh/mmHLQuQiuwO3AxDQ973E588Kf9mLRZ2kdYfJGClFew/83hG/RJRSMJJQre7W+fsMw14npvZhuCKlzCyo168mQW4x1IZFdCxIn9qG7BQF3P5HjQRxq4tP3bjCNDczH+p4s/j2WNGyJQpFgekQKRBFZ59DcJi7Njl8Li8Pwc7HbwI8LOAA++kIiyk5xKC4UZEHv5e/ZOo1hDukKUd+3yp4qSY+FHU44sq0EusoJKuZFmLOMF8zqVVEQT6gJDIRA2DojX0X9x3Palt/URTZ9v8Fh2Vr7sFidU+npKgC7hBKa4+yj7zOzq2Si/bVvYBR3NZNkpSldedLcVE7kNMSNhK5isFPjwaszVZwFJVkPb7YBRoc60xWHqBs41e4rioNtfEH2CTQVghwSo6TI1I2Fx6RpjMO8cK40KbQtayYjfNEMymXI63NI8SUbvG+9xI6T59UtjoVOdUU4QgoPOJnY3DmmgRLNu8U0mv/fY+1/dLnZGAkINdYy3flF2o45+dsqKoe8kSlenS7bemRY8dvNjQIhADFx5mzuo7nMZl0KzLwhSGJZNwtnsWC0APdt3V211OD3ZxYrPSxQ+0HdRgA4ag8vhvpl55CnBdwPBYpIMu8KBD35CeAhbz+yMqaEDXuX9b+Exi7P14ntTO1WLkRgMGDRpjgnFhWMLEYuNAd+cp5cg/3jr9+XS7Wtw2GzbUuK4u9C5Z7Ytxz8Hna2k2Gl+3CgCYQAuOH1jpXoFHu2BtCEoEaR4PiPafeap6WE8l+usr8yiAQFuKqKNS5SeHGooPvdNlzZiVD08S0bqGoS0Zycb0n0/ewLjI8A03yTTzGbE99CGEafvlFw4jkyegiR5bNx1dsjyUFt2gxdikdONBkpwgGVov7aro3iQSdwGgKJq2HFPbFhOXtj/lLyLCmkem/uGeIDQWuw4qogI1hG79X7fQijEPdzRW7aaoJIr4k4I8zxk0uRoHMhx6UZEQ4lepIGYPhBmBRb/z+zp+5NBterFDWK/Hc+SwwTHB4Fi7/+aBng8E9fOzysBGr2bNgFpJWwdACzA4FnXi74S9OlmarE7CbR4U/DkA16PmVrO2aLG84JDG9l3PLo9N7wXhU90UYkBRe61WFt9oxmU3NEYIYCx94BKcvlreFFgb1kKYCBT+3iBCJNlFDZor1rsCdpRqmfYFjx9jzQh/xV99yo5CDFweoLJGDF4N/w0enTOovaDUOT2CJwrJYja0bTo+iDWE18Qw1jHH/OH+DIvy4yMTueKH+sbMT55eDWOpL6jrPXo91vJmBd0fj83N7RY8soqlVgezJxCx5oV3y8yl0Tvwmuqvc3tkl077ip1uPv1csYp1ldx1SeYn8nrLhAT3sD/a1cjctCyRziQP3TMMafIos749kqAvj0acR+vM4dIOG61863A+wEpn5nTADPWj9LGEu12wXysjF/HAkQEJ+aDvDLA2MIgJZh7EGoHpyLAsdDlb6SaoBcuKKTPERBJ8TSSrS0mNS3/xrdT1aD2WLADMyowU8VJ2/ydBbEyUVH7iEJqOJNhfsh2mfUwyKcIZj7v4TnSQEt0H05uSjQuzsHdvTBb0PPBFrKXs60FvpQQZ+qhBDpxeOicbbO76fOcmW15Au7Qvf6a88JThspbdYIb8W+SVdz4QB5L4ywg9kKPODlpCD25TTFHmA1YYfkc0jL59ahvIzt4IuRzrqkqixltFBaAEF+sqjHvU3XpEoASdSeu3BjkCUh1VKGf87q+H2SJoZVi6dZYTUQ+1K82eUIMgeNeqCyGBWjAbpLCygPehH1vfG17F0YZpO9qZMoXOajTxPcEykgJUAMYtOXDvdI1J3yQdGSaeYOfi0wV0iAUoLpk3b99TCbzPtD9M0vCwu/LhAATa38BAKhnrDQD+uvTVUvoiQSL8gBLOn6RKDU6dvR7v0wkX0Qk14K6Q/G9x/YluwZc63+XTB+zTixgu0SWeZkxzZj7E2Q6UC5PB4JL2S/zv2d4DFFXRwSF5Hy7VIKcJyt+pithZQCJKtVIN/7u18YQ0q4ELWemTTXZSIO/reY2XQNFoIanGp0yGmoDTXqL/pMvXCl1wooGKoFOPMcqfi57H8GIRc8sM3Sna8lqOx7aJBCW3bm7HHIBPhaBZTR6SAESqfB8emCg2wMi0EvGIGTz2pb4tstAiUS/1gvPedphvvRC9RKXBssQ3XIsWLswMluzmSC7qKcFRXTzYuULtfozQ5n4slE1KAgzRq0YyZCFKrNJu9XU8n46KTPKdpBDoMqXvIa3fMMJQy3sUS3eEeg6LT4TCsH2H29HbD6dqCEphhKjtDLPrReXyxrE6+GiORT7cPr8Jl/qDcPdqHfSQwBo5gvII6Zki1PEjkVQ3KO1aVLuyYXeYxJPhCU8GpOXYbracc4qCxzf7sw3XKAo/pI9w0oE9h8AQE6krgFCTHLpo7AVElHU8SZr59eFwQa/KwhxF3EAc8dKwgdgf7jQE2b8G3/Q4qVND/f8rfgcNiQhIRw2PIv5wK+g/DMd9dV6P6slsi20VRX4TWM8khJyYcrqzRv9LXKh39qAbdDvMzzCnhItqsHEnuRPSA7jjThhGQY/2FoyJlff8UydcNOU9k5SqD6Obmcj+Rl8h6Kye/LKwEIJ2MZQ+dKeUZErmGkRJubXvuoHgOdsM/Wc62CZxUkpeuHM2d9Z1gCYVHaA/F9Ip8xw9EflWpFGbdpy9FqPtjNgReZ6/ffaFXEALV8xVIF9koIO/v+mPLy9IINHARmZIbO1/s07MreYnghtDD3Bid248S8tfbRTv9arJ9kZnZNkKaSjrQndk20vZvpVgMpukmcu/YAtJ7jWc1DrdV3Wo6MEjnl6vDcozlBDtOUSfqb+S1y90QRcaU7u3tSUNrsXiPSkcd8/8itCHfGUR/2zzY1oqyg/WXiBcYYDR2/iSPWLldW40i17IOoBCkrXZQqF6xZmyT09xhXay2MJ2qdjhZaNRfOWg1F0cX43skP1VK7hzsneQWPRmNhPpLJIwjPSZizFybk/+AQSIwm2dWd2sMyrntPLgHxBsGZ3dqk9JoRm8E40Fb9ridobNDxunLBjggj1NvH0+E5a5W54zqSX/7Zd+6KY9GYHWcPXlKWqwUTd8BV9QctTfGxZ9zFSwtzkIgxuV+ab7m44oLagyfIrbvP2y9l6+EpGOzfTOrHkEPj5H1yuWqlOQHZ5QJiU0r1ggybYyswBCYQrW4IaKp3ME6GdhDk+TvjS4kh088JB1vmZpFicXfHpFEO5P6R4/XDyTp/WGcCssx00Eo4H12V0LXviTvZFKsHcJai7C6azQ1NnUj9NlcYqbJNv+mwlTKqmTxNuA0cTdTg8cIh35sWfNCR7aru69aDgv0NCscKUrAYhHZZeiF5++Ae6pNzaeekngyLy9jxu8J6odjqvbXo+TfVvhZVtB7vMvXSwzmoE6aCmHNYoPqMmEF0CewEhm31qgRRJkYT7XvrRwCqW+XV1bk/Edkk43sgU9u/JuL4d9P3DvTF6twMx7CrsE4Tp5eOFpg7iaIE2wYuNLWQ3484YYzBBWqWatjvrISzEDT4wggbsRLCr52YpXjSWZRMIFkK6gEbWTKxmVTThas1zTkOxGgH8JEJWUBZ8cpcEdKCmiKfu7rAZyWNR2utQ4+c5sKH8uBXFxBUFzt0i4ZbVCosMV6Q3JtXyGW5WuchQXvpUhoQtYafWi6CMNQMDnf4AfhuUUoXp93zCKRwmrr1JPxMKts4zAs9JW0ewmliXtBrchRzSEKU4LNMKd1qBykq6QjT/l4m0FGZjHxjUKjbdqPLO4tXnl7JaG/riisBzAoa8F2zGlKo4bfJYfoIqzq0oeSsFVrfF5JIfbnLah3pylpoI/kloJKAd38CQJDJarEN9akGG0Ax6o4XQChj0CNuz7A2SI5b2iFLIZmBLOcBxNRH6rIWpY34vSwdjQLb+cGI1sKnhUyT0Yp5NL+TfKBaMgQq8XUcdh2dSfIcykpVN0sUz1Yb3q6IHmIVobzQrcr/IuaGswrMxuX566hos23RNU4GM/9CXz4GnC8HDFNhBEKJYjwyR2lv+ZBKBDYN96KaNwSkJ4TSrMr9e7Gc75S7UOYXUpMfSOwJ0wi8b3nPBSCrUXuiNCzIPU7eq19TUSUyUcPe9Co+fW7AKXLL9q6OIAvc3Ob/FF858Dnthl3HwBHM0lGqPkw/rDwY8MF82KWuMTqxJW52KlVC8EGu3+z8GEgAH6KnR1HxhNqDA83SaaRXASOLmtHY31VP4xPxUPipnAmJhvbM1gaRFXpplt2un48MjELNuBYD3Ys0T/Gos19oJGZ30mcwuSE31ibS9gBUDMzn/svZaFiKCQbLH5tcdUYM4BFas9b3fLLe2Zj/CT/Ju9ZKnSI93VyhYVaz9jxvgJAyLfcDt3On8XLlU8eSPMtlgh5duz7aFJDdBUl1Iduo+c8c2v6rRBDbh5rGH2gTXaakRxisHz1xieOPDjsqwKYjBPLVhqnj/Lze0cJKZ+Twv9e/wx73kNXtq76+c7FMG6NAyz9b23gqGwRk4C9cnzLDa/WvubXlocbp0oNnw3aM0SRjAOMgkkr72WGhKTNCrNOdCq3I3DTMn2pR3h2vnYaPIuiw32D0hPCq5RK4oVo2SKuEbM5jV0QDHgGg96AatUbMvtD5BRYUpJkx6bL+wJR00vdsVQRwCm032c6UwgUgE45P5JakVUKR6aUgLCwQvIX1FH6iQask2oVsWO+7MitykAQKcYCE0/g737DptAHL3zoddjqkMb8nIfWgcJ0zhme+1VYtaPgzg9xs5pDQsTYlTDSY0/eCLTaKgWQJKCJxQ5TOS2H9OQbntp0+4DgNZ7Yoe8EfJCPxP/0Um25lF1OWMx8DYFGYk2sC7bOgz2c+iKWW1AL/CrfotknCr8UByKgEoqKBW3zqq+/K9wCIvyXdSHPz+o3R9HbQr76LLRPaKYNfVyIk8TdoqOz7gIxDyKA/IrPWCsf6v+7VJiA27wPXrGoBWMvQyV4nkbt2A4me+Qf9QuHRNBb6lg36zKRXp5gJFDwPO8ChstdtHCgZN2su4ZjnHlR2lIeaqVBy2ZiTTadZRuyODqQAWcvTAHMIX0zsyQekIFulxRvwt/a/AsbpNoPYPNLiAS2MwgQ4TDFNn/kA4wWcLbkMvtceLWfFGwKkW7SLnaxjRHj8kpQ8b54D6cCQkEu6x+sKjeC77aRG1JorPOtIOBI3Rjh8Ro1JqTD+CiBwQlx9M7sp4ZdW0o+aFUWeBH2gUCR8c5llOhnSzjzmDfA/oCH0A7M4y8XC3hLSwr3ln7ANcZcG7l+IhCvPJ+J5imRfe08UPTELqPPhD2wcWK4KnghMoRlzN3b/CWjGj77E1iZppipWIheip1EpyPe8Vo8JJWeBbSq0LSrYzvzuCtyY3QomjlQlBkR6dxlIzkx4s6kR0JG2BDbtShX2liS1RWkkc8muldXXJRxCS/bjoJutx9EgKiDNZ7dHGJpH0TVUW+WyvKu0ESBdcYyoT07glAIIies33iXc3sX5d96ZCyqjbZwnxj9OyQrOvOkwmAz21e3ElAM09oG9U7IPtLqOUh/JLmv+ujY76hvIpq9Pu1HciEiTBww7kQWNHoqMj5UnAmyrvmbhdJAK8KaoJaJhl2jGwE4tbEVyaCvtqVwAPqZqf2gpxr6ZzHSYzmP3J9wMAUOIcZbSbERMAmgHuEqxMOiQRVTF5deo4VXpC4CxBQQQSBjumvMW4wSvfr+7ws+YbELrjLY/ys1BlWgbrqkvgiMEgisdzFnd3GxaspVNqAQGAc0YVBCFwPzx/9k52zzBFIUKZ4gqczTfh96AMYOcLCYpmOcaaTYy8+gn0su1YUO8cduzSPREAq8wd6Uy0U3ZYXkQhElvwB1bLyF22qM99/gzabP3NMmXI6+hTwLRJNrujVEFCniVFrojPvkOBoEvM1bhOtqXZcX2Vz9sPct+gpsH0p1zeNwxuIXW7klZP7313KMa4JRIQ/jRx3UhQ+XoaGMggb8gcdcZ4vRyQuIWyvBeAjqD9I+qPkKcMpB9erTi6HSv8PZCkQFVOSJx18FVS6hWePcscXqK6+412JP644nlboHm2uJV7t+NBuLdSKx5fcpr5kJcShoA8+dDMyuI1IVoVz6z7TSVKSJcTlp8VLcuMtqk0C4ExA217qs83hDbL0anhe3WqDWIvECA+aoADSWnf20Gx8GoXR+cMVO9MnYwz4VjByV5CLLfLOCgCciEx1/gDVRUiyT967EAOJ5C209xZNSYixWXLptGReFqLQ/P4gKl7b7TtTTzr8ri6XD9PZXpQG+PIbMZ6QTTBLEVO2NEfQJUMSKy2ub6pXJ4j1RGMVugFPyiISh9HzMRxiKgDk9udzh/KcY1LKxv7liLGQW/VHpYmPiZNmMFCELozAolsA/VBeI1+2Ya/G+xOfOUfUqgQlKYBuvZJEz4s/xcUpGmeEolbUz2Wi84nwgPCC2MzjgT5vDJOjbViASCOJXdUe5YkqEUgtcVckHfngXQ92MKJX+eqBW7k0Ts7OhbkEYftoABA8hWGAnABtllNJ7ureTuoMgEg5cXXakMaA5xxpODtB4Z3h4tF/rLQz8s1x98SoIcFXkkVh47lk0W2oBk/MB3vLAuscCTP+VImBjecYEMfpnjeFWf4IsMu40GzICfyjINqLlZWhISSXbF/ymsex9P24WPWkvlA8BaIBe0T14DFYYT/xpDyJUXNxZ6PK1o6ZTIssrOHchT91gsrlvlL1bq8f9jXFukRqtfJyyo3SgBNrr6LAwEsoMXxsr2GVjm8HG0Ab3Gtdx+DsYym6OcjZwb9hoqeglVhxWEr1VdbBfqhFoaI8xB6orFCZ2hPnvsqO25rN6K/JdF5gaoT9Kl58gMqMD5iu6sePPAfZSLHq2NthJZQZPatvlciHDlX7bO8FVrFPZ9KeRIKJRRmO5eeQhHxaacmTTptFT87V8x1mMOnj2t4RgqY0k+j+jJnf6hpLUOS8PQAqhI7VruOUUiAU1AJq4ZQfk6XtyzjLddjL9DJz8cknE47ZMflcmXugfW5VprugEplXJfE67QTovpg3WZdfRaoXDwAPnnXS84i+YK8mMnBiCp0Y35e3khzxg/oyunS/euWYCS1ExDHU0dlqqUzeHm/AzIpSTUhpzr+IxiiP6c/SNcXTpvwcz4BRKK41Z16uISEFplpNbGGIoyoU8doikadgdZYZWcgEriGvI9R9gB5SOG9ca/TDFZZ9UW/hgip21I36L3+ZVymvgTnlhUsIkFKu63xdJKQ1Qvyie8/tfhTel9M1d9r28lrdfZ+QHuAoUAC4RpFcAA7yFJdzvcPQlT1onQRTfZ3BDIeu8LnHhGRT7IpM3x3fY0DfOy1D1bGr0rZjm0cOi25ZMKsOpbT98GkGqWbA3Xg8Y4CdiS8lIZS9OkfgBw/kaVl1YTAPUsPsdOfSlMm3S6XJ1wqhg9QCyen77UJ+B+06nr133AIIg6D+w+/JOakjPD8lmUi/JkHrC+0lDToEzWIg2etRT6vhdNeBbEZubZmVt9Aj+5b+N9kkNv81bUhNou5Sy6eDK3mOn1AaedgPRfC8ubAHdJ5/nsfQtf0giRpXzglUmMAvfx6TYA0Ltw4PpOSRIZ4u6yOGVpkgxWtLGRsbJDiVuje/esOTnJxPD0gLF2WLPGahpOsIzSGnc/cZlW5MF7SSYgJzjRUO+j9ZW7ij5mJXeN6JZb2Lq0/Fh66v3F/mUwaX/9i0x3e2lXdyruQGmdxRL5GHu/IA5jLStBuCCequ7aWnayE9AirI1jROCaVAZXC1Bun+t8/X07BNhqahKq0wD4xuwGCgCj8NAnzPimgYo8u/Phh87aRN/uQ1YMJZJ2zjKUXAhh0K7pBA4f0wN7ibz+CRkDDD8iXcfR6CpmBZoeUomYobDE7QGFYPfAl34H/M4u2GwhkCHZ7J9IGKdiNtv07p2fKnAH2oSQ5wfBriQUuQE4uaFzNB0hlTpvQyE4koEGDojAN4TdEgKX1JuSMBFiIeA1BYTSVzbGh4ljWT67n5nq7/ixu2CxusQdjRqfDbwImK4yM2PTK56uVu7ikkipIr/EfPECV64obgqg+MIajKWf7wJ1uhtucUsDdfTnLUOgYhcAtqd7kUcUELH5JKAC97A7M3STLrYMZsWmCke2Wy08ORSv2cEkrquSDKf3q+rYRZ3CmV6tssnumQBKzj5Jw3D4BRPoHB02QqQiz/2ZFXZuVfkZfYVmRhwVdsFUQi0pqdIb3DCF5GhC8xTSUqZ0qim9Ab+xiEUUdg71Joi9XTfbz0VSwEaIt+0hOCPrwrUXyKjLwAtmGWr86RNIXsr2uKeDh4mFBBCsTVAT4NHtOz5aHTEvvGa52mm4jj9c8jjdzJRoZXSBYvXFqzcxjNhMnMBscfKFu2SVF37ToVptWW5R7NIywX0wINFMU8VQJ9daRktmoJgvrkRnkq6tBuYu4PCMpvEMmnHrhi+/+gZoruZXTvrqlxKXxKti9n4q1DYXINKscYITlNIZLe52/rENd3pwmSXNwKo1+ntVA1HVR3w/JNTZ5LbJcXRO2Y4yRC8iTt82p6eK28gbfg0J52jWPgUOytzPRgQRLDrNQ3+j9m74hRRZ0FKG44oA2FszccuX/07EID7eZSUmcAb8lLfuTzWgIzxtRif5qKwQnRkFp0N/Nz/Fh0IFHo17DlIeqRHm/INiJ8aRay9zH5WcAb6Mps1m72b46Xedlyj5i9bE7J46BaPSsAYwXxPmdkkW7CfzKOgLvx/QJZwACrxzc2h9LpLqBk1lnnfGFFuKwAWuqjO7nAfFZBqaAEg31fEDNRnFbdWuxB3i87s8g9QtdFMOazofw0248UYB2PJ/XJMtV29g7C75/y7xUA4q0HtiAiHeCLb887Su8htaihCO+0FI7+j5nT11RFQPggJo2d69a3DK37qgV0SrIIr47vJVPxMJHaDbAb8cXRq29jYJUUuP6mlpKkk20Z1vlA/PbGnS/mY/xsV5pTR9WRn1AR9M9u2OG2ONM+XqavDB9T7MdL9+xUFVwaBQeUk9brgtIn9oCcTMD4oUnVuTnlw5EVrRnlB1Vha46vZuwHmtIagkyCKS6SW6GvXrEoETAqWU5v/nt7JywvUUYqLz1lcXtCnLvfjE+mClyY99DW2j38rKYBjbqWvozdRmR+rLbeyJxAvK3IQnmavBAPIAMCjP0U16JE/4uDCj6ndO8qc+6Oo9KXb0Eh9SBKMrfVKPwl3CI8HL8dcsnfNyDFfB1QK/SxhgXiTWJv4lpERDSFnI1mggFbzQ6BwDF/BBaEKUZO2sovtHqHuY+q+ku18j9cKu2HUJOBp0325LEbwJucKRVj3hdN/ES30VOe/+Ce3PowQvAgattDFzs1OH77kMqrstlXUVkrqTh88F0UwyqZ4neN9IUTfgA+snOeXBNW9wnHef+WJGB9CmqUAnlMfCBRkdxvDbwlR+QPS7z3JcylmI+J9pnFAphrFdCWZ9IKQPEMhbUQRNfqK5VP87ltiu1nwytxwGuECw/DWlcvRj56jZcTi2vp0L0YyoyyokANbg4iQAhy3rJtUwa1WqTTulCRGiK3azE1R12B7d0aaHaTWjZNfSnRo3KRtcdbuliwTrijwC65vbLG7Pf86YV4zUCMMgJtn/eOdEr8zPeqxw2cB9ns4oCCwn22jpX8ilKy4ZREY4K4xea4oV2HQj4aUuzEj1/AbJVLm5P+wyCSTz3FLCLjO4nIAyfhjHG7LIotp882XSrr9DAlINz1sbARDxmapi5dYkI9sUjWjbrI80l//fYWgueo6wuYL12q1R8YkHxZ7cwvHtsA8R0H6hhV0yoF3Lspp3vz1waVEq2bKjGPVTxD+cY1espXrYYnKVzCASWmfQAKlKP29VOn/Y7vYmryW8pr39aErcQL6w5iqRBsSkaJ79zWe+efAEb/yWwvny0NV5efgUYMEBd+cQkNnpK+j7xyt4ua6O4th0WEqV7SrJefYLGsd0MRndjISU6S72nTL0bLD6cIeM+AmEFhkeamLePXnlhLVRrFxV9PFBdhdUCYzUoU/vEJDiRu4xEFVpeH162dOl4B+tEN9Ang1HZMEBR/dcYsJACCZdrBmhJBo798Xg+98B4OvuaiNlwqIU08CYOQBYDVbAekcAKPEW9Ctt2ujdyy1xjjTUW/RBQWZU8XSYNxL7dtvJ+ch1umv8hlRL9Qg7u1TrZvN54GVxMh4yT47wtyrv7pBHknM+VR6ClvY1bVnE/FumRFIPqe8KzOi3RE4Agcfk+3Be3Ih5vqpAsZFOAMAK9yT3/rhMurkHkrxZANZaoWLipGX9y+XruFJsDiZiT9QndqK0APKv3+l+dRhADaxnxyNuZ1IX6j6izjf2PtVsDGf16LnWDX6We28tk54A1QBoqlLldw0DBh0elnSoq+xTVqwdLgkHLF2Vlv3htTOmR7M+MkVSB6qgOVhzqQsMCjtgfdsd23nvZMRAkVPEOt1EUHEC6ADEtUQdOg1SO/qqUO6HyJ6flspYjwnjxrn8v8y9oY+9/x0X89X2Rp+l3anDCEn6OGWp9WXQyWwEf8OaJF+xbEJ7l6coLGOma0+YSqHuvgRGXKtdJvpur+6P8xGnoOOqzMgl55QGAGMK9Vcrj0EJMWKXT2QLY7ZHZdlnASggB1dI54XCz/4iE+qPf5ZiGElL39mUpCk+W59dWqvIrKuH66M1O9u39dmpNd//xjYCRXoexfZDZp9oI9nLLpnj/wg7tCAHnNAyAhCh66XQz5xVBV6A2lYC58FsqyZA5qszX38cZ3NPOkgu44saj0amyiYCGzRqwGyx9iOPn8ChcIsY0oMXD3O+OS5HzvyzKztapT4p8A84UCW6t/sn8b7cmgz3zCN3y3rhbvS37EXuT6wHqI/vvaDvUPk4Nkgj8A72CZeAeHbYAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<PIL.Image.Image image mode=RGB size=64x64 at 0x7FC1D11E2BA8>"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from torchvision.utils import make_grid, save_image\n",
    "\n",
    "img1 = (t.randn(3,64,64))\n",
    "img2 = (t.randn(3,64,64))\n",
    "img = make_grid(img1, img2)     # make_grid 可将多张图片拼接在一起\n",
    "to_pil(img)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAaqUlEQVR4nE3aecCV49YG8J9IJVROIqQipdHQqJJKSZPUiUIkRSIaaDCkUgmFCKGMGROFImQoyngQQjoZDo55nofT9f3x7Dff/ufd77PvYQ3Xuta61/1IIrglxKEPCkuvI/+DkOIPx5zvHfgtOVq6EWdpGTDpjuVz96S7xSxtELoFb3GsshUq8ybbSg2VYpwufOsD52UCGUi7KyVBz10/xngz9iByX2l+MDhuAcmXTiiNhyP2bMcpjtclnSXeWOOih6m+3FZv9C9EOF1ycWm4ES6xQ2dW7IMqpqwvlkqYZKMcGbgnp5gSqmA3G57JK8ls1n7mP4di5qI9tW2yAlX7Wpu9q/O1ETpkUbKmTjoevRrfjLrSUL+PZ1ztlGdn4x1V7d3ZQrLXzv2JXM4gb7Z+I0iNQuDdRUyMg+bLXs338ie4q6WtcdeJD+maWe7VTDDvmMVSNV1HdlVml1DDQfS0g38w4JFInUx6xrs5oDNNsm9Sa4b7ypes2IaJXOnHpV/4ge9Kft/yWVFt5nXJITAz/tuqFW2FOb2kMfcX9gNzxZnbb0jyStkiY5KUix96gHFoMawLR4Bh/5ksztl3goS42z/gr+4y24mFy/fq8F8nDzRKs1At2E+PpZtrB/kq8su2Vt2VTyAPy+4l5CV6mLlfXi9B8bD7Di65OpHU5q/1LaRDIf1h0KtcnOZR4W2j3QufqMDLYRtSx+dnxwOtyXC6agNXEJoyJm63CzsONfizxLRSJB24smqWk5Psz33OLSwlzii/TU6Kz26lfpzmg8Jm4eswBmYOfb+8zyOJNUVYPuDj/+ecxGG80lKtrJslzM6pTErF/xfHhcrFhIOOCcbIMbUeK8esG0nSPFJJPG5X9j7yvp5n4NKQnPTg6RsHOmHjbbC0TEDuSAu80vVntYODtNhZq9sT8XDuhh2MeMmcVLjYfb22zVr2vl4/R9eSCogR2K1C12QoHE5qx9FgiF/uIW7Feqq58ecNUS/WSBvRJ5mD+mgygY6Fcp3IFfqIr5PFRxUK74KM1Mj0cSWbPfNuLlqRGGyLedyFrmGPpC0b4Bxd2ubXNcWIHRvlvlUGymGWuB31PIWBkZjD4vDF2ibjjEruMxtpll72dlnb/MLNWIbYTpgSSd5cjPVhl52c4LmHtAuL7vjFJ59H2qcWMiN/ldHgVqGDTz6axu19yh6GVi4Y5lgLlQvegFppY76KIXY6LH8eHob70/575Y6DXTHZTlVXjVcvbvtoWAkYczJm0GXiS3JcVIbXr8FwSfpuIYUYNIVUL6Pn9C1++eOnsbvLOF7uWrEDLqK8pHqdNMjxHpLts1ENeN68rns01sJAu7z2LPVlPn6rKtN5+IFj+bx74Zod9/7Whqrhm8v3oXksKxOju5Xttm57r51YWvDPV4uMDHXyjzg/bs2lMe0IN2Rdb6ScAe8chLfjMBzvmn/frscFe7SUJc68AtrXcRbOi4fLYJ7nXFJE0XlfdUGu+I7XeOF5Q526J2jSWtLGzrvRv1g8P7ouM/3hCvpGFhgWTMibVZs2OYIcxHSPMqgJzmDFjuBhwqLKRzv8lEtjDVaEyxtNp9FkM8h31k6h/B6MyWM/RVoKj/Lkhf2sELEWDuTPtgUD/GTS95x1s4iHtFinVQpGyFKYhLEL6rzdGGkChtv3pO6jub7VMeEJydQ2DqJ2HSRNW9TdTxqF+vFmy0V7fO/uwjF78FeaXuLuqO3rsyI0W6fXjTJwRq2oU8JQexfwioap7Gm3aP70HcJxk38QY0okPeYC741M8gqvtxz3WOJGcihhnDry1XVUZypbGG7Kg/YOWnF+wo3G59rM9RUHadKjQMoZ3eo7qeD9iPJeg1t3Ri92MD9LLD0bJkx/zhIPtr1bC2TIiJe9ioxM5kT6FyB5SqOuhanzQxET4V4XgrWro9bP0byeXN0H2+wFDxTwmlqkpHY+MUoWg2au651mEnkoDpR8YHpZSXZltWpo9Xc4hhWx3Cuf3b/H4DwUsfdNsVNuEY119kjUZIdxT6csIZw5nQPKCMQyA0trddkKfjNqU+LY6z0wpBn4i17tZHNkAU3zdLHQNryMZaXkPVQMRQYaTni+JGFvLz6DHC//mszYbsXOa0/f0FZ5JkTIgIzwwjak9V8PX/BGysimB9ILafA5ex6EhyY+s9M7s4XaqUZ21o7T8tltaeNNyYBLeIhkBhmFIriy+hPLlJRN1IO0/c1Bqan16BIYZuI/evh12v5+XcnUnV+1rkQGWjaKbG55Qs7srTT+OcuyVnCkp51h4DrPXJKmYajIeXEjePS1eLjI6fUdUh6HymhB8zJfdixVLhNKJdWDpU06Htmji56tZqrn/b2LoZ/ZJ79hbzKyZKpxZTaLk6U+5b9xq+H9VGmVr3AA7hG6o5LIre4atjYnPnQEmpdbf/hwJ7SqzBGzMu1p6R6NxYCxkBcmXpq9k0t5ggbvFD58Y1lVi8SOk5FkX7J8YeDV7VDUBlqXUtWsGCaY//FmT4L9snvChfrFp+220hdVedAnvvLjlY6ThjLmGBsdXhUXl0A8Q6kMjUMOnPOorcS8iLwOi2r0aUE3DRtoRhYxT+5fl9vEhyUjud6Afic996mystnQiugZRYaWozL4dYcWTrGCq4oNJxXKykU9hm2E1meWPHipfXxgW64NLiptlKPbP2N17H2qmp+l5rz4uNjwgCR+OrO0+wl+NmdsiPU8UvLleVFpEwYeGj6fkPbvy6NvjCht2F6SIUp8XhD6ZmziuOzn7EQNP1q3zg6aDIGLXebmUgh0KRZ51Q88B7p7esQwzxkf+nqhRW5CbJVxmJfOt1zbaNSrv9P04t4l+ti/2sPDywBcfOqHNZKfe5+XXLaFqYZkRfF9DHwNdxtBVCqrw9TUvXSITNmpot01I0y7Pz10Kmn5TnJVP33fNOOhm5QXxyCmSl1YzTJLdJRyW9YIXQuXbzbeyS7etmLN7EZPGBCZ/HclOJZcNqwE3SeQ8/2rwjmzy4LL9/YoUscmNTyBYnG7+4AD7JbXPsQjJb52i2epfBbc7LNWLQvTb5RTbI1KzQYfzjeY/Iaa78z3SGK0c1+NrhHepn3W0S3bUXU74qDL0vK7uu5E0+zhAqg4JP4xthCyegG7Pk54sHsh8w9Iu0p2XFZSo/JvJA6KiqY4mq8r/X8nhlxJA2dcepLBcL52ydY0L7F9ZD21ZaxH3Y9nHSwHRWQdGeKwwvjTi/WuZjnyts/lTJK0/NKc44rldmoQiQmHXFlkcRyOt0NUyrE8lutUSvidtbdvaz+rJCdVKkXJCTCb80SlLIdeJY9el+NjiA6a1Vvi7WwKP5UqZ8fGzWZFXdHAPmzuzA1Mk2mnLCFTF04t1QnDg7OLs8p5GFYsruyriZ05LG0tWLUq3FGvKAhyI4/ez3icXMJE/0sf8vOG2y1a2i7BLnd5Q+bdLufYfvOdZVhc83btDDzAP0pAMn3+wgWsOxcuTsGBMRvnZs/Xu+DPwjO19fX0/ZzGy6O8/dbK1pcW7YIzLEQ18s2fvmnufyflV2YytOR0qF/KmgeAXpfI0ox6BGlsd5xbNnALEIIWL5SXT+Nl4hDt40Yjy8YFsy4hh75Y8tMLTT1eTOxYRO9ofLFFhpkjS6mQ/MpFlKM5O4GTvs98LCOpJZLTPi4w+3gJDmKVZT2oMrc4vc/1izDADsdm4nb2KhZPBqRnsWmHYuOX43h94W36Bul+2wmHf1iNE35WKZTPugLYv5YxxqWEP/KvsNPD+6d1uAIDSMUYYEuTyf9w2v6kPZlsHknTKi/uzfgdz34r0BAaDRjB514tdjhccuGjTUo2P0pPJ9NJWTnnfHGWmVzdKUzaFYdEA4xdZX0slNPtGNrleeTkkW6mqbx2+S++yXP/tfBZHO5jjWsUwh4sR5YMmUTaCR6JC4qDwy2FuXbL3EGWdDhzcTWW+p+8RV1JI/sUA/zkLwz1ZmGqk6VpIfTYjdGk6sZS3gKdqvQzgZbghi90tG+pp9WvLGBtigvCZF3Ffjaep0pp8k2CJjxUDK5ekuA1FULLYvpmqbymMFxew6BScK2/gMxQ1EaxlO3af0CdXwQth/iYl7xlZXDlK27HsiMLL5C3S3uNNqck6BfFD7OkrNVaMbilwEFP+1LtZ99jV3NjrkEWiqRObH8SeJNOrhqRHS+IZEo/nytF3KHKskvv+/7axq2FBXvHbfXsB3+M9ophDIHT29NTzEz054HmLjgd0gG2x1b47cQ8Ev25nnsvPEHRE4mwdRHpx0vuJbq77n4WM0PP+cKG0oHkZFIckC4Jz8syw9Zvdwtj97poXki5/rSlHC4MDtCeaGhKSaMin/bFisodo/OBaOdUuE+3RQXbvJq5sIP6bKR8UlfPN47jpcLJLdYk4fvl4D32vfzdSrhdLMzGMsD1QuOcbmG0cavHvy858VRxXeG+rXqFHKj+dPPxqd5xBQcGnrk0U5wvr/sR9fv1E3d/4ijEisCEFws3zSMN9uLQpMIooRP1jutXFCBWX6wUZ3ZyWacS9SXp/7JYmg1X3mHa13rZQL5M4nwlQvHthYmrwsscaW2fGs12Sa5NJKqKjvx7dO9OvORYRxe1q60K7ZjuP3xSmKOu8UilggA+0nl2muAUwhGz5UrEC06Rb8lURUq/pNuXy1I/mLRtM59H0xLQYQmtCyqiulUjhOkxJ8TFpRXiyziXiu91KiKzeHx0ScgyrBdCp62L+1WCziskLUuqbKFYmRTPE29lWyK/vRAxhoxn4z8wuK+Dt7NTXC+4iCzJjfy3j/9VUYrq/nyOH7T5qJvz/21tBkUj8etnZeYzjTnhHT1KDZXAgvOOfC+1z36ynr002uVL/i2oP9H5i2CUDwTfhqJL+VihXGsNZJN7Wr1M/SFeekwtTdgTbmT33nR5antirO1RVyNYqfHxq+Wqc9VhWLVdnk817ipkfOjgbR3yT5JByj63kLha4jVC3xeWWOgGvxqOFqXMTr697mBt9L7rj6/1rIz/VBhHfM44uSPpnQ+QvFlY5LiyK4iSs8Shl49/hZ0Z3U7XIpfMxN1wGfm2sOTGe1HnumrHha/Iyx85juYi3mvDHAsK+54S7PrS+tiAaDiL3t5CObIZaYOUTHoPWNHf+d+Bap6gUs6+Al1+Z6rWYnJie5jL11FLAdmyU53PTNoEGWLwTayE8kUWmSORw54xevEeh8YIyiUnH106y5+U8xrvQGJobcnHzCZLJhfB/kTVX0uY3tF1+NM+2IkYvXIbDxT9FX5J1lpwzfjXN/HIPjz5e1npkQEFmf23+Hd8cEj+sPP4m0ax1+C1HeysKWn/uhI8L/nJh5KXnvF1XzAx8c/fCUN4fstNgQ1nhB2bs2aw5KDIiZXf5tYLnZhfSkG3MlfAezP/9ZGJmFHm91UfzwjbMk3sqx4rud/W4VQmF1k/6/Fn8mWR8GwrrKCdn3JDntwCpGmEAVuZZV3xsODqSy4qJp074tqyfdXY2qwWeGjwqWB/Wqv/OsnLn+LUgWwr8+OwqJaH4L1i9uPIwZvcCu1N+Zt0wEsudPzjebd6Eesb/Q66yMxiyJ23s7h2xvioyPpUm0ALi/VX7gtqsBthraKbHwfGZmrKmra9mVAGOK8PdLgcznKrs8d8q9nG++QACwrk9/h9HGbkH2w9KJdXL04mWthenkrobG1R3cycZQWJ1JvjHEw9QJ/o/ydR6xtuRXoKTrTrD+/9kD49/DJo3+AzcUfmFVIdWTJH48d3slWekwXhuiQz4hq+CNXw7uX3pLDeTLUfvJdauSlvOD3BdlOLnA91mepe7gOzqHuIkN0EV758Q6Z7JE6SC5RZp9+Qb8Ku0jj8bC+OSXc7vmAUddX49dli8dOaO0MYSF1lQDq7IpyexybmIvUC7c+nGQydykmlTJMnFHeV/21YEWebkDn6lA4ycaOz+5e4CfJ9Zv18g/qQetMu2qQLY0KtfMr0Sds8L7mEBvHpq6FSrSISMyDm1q9QoGmArYvEWXxO9Pfy3DH3qpB2n0Y66tqdqaHcIUtZ7/4tMIXJHxvBndyWo8tuuH7zW9EkYOenl0ujk/VSlx4eKs0qxVlx+f9RvhGuKZ7Oc8qWHIzszusf7HuXPOj9c6ZPLitJB+siZ/N8cu4i2XfyqmLdI1F5/2k0GHm7mrbnvrKLq3zJaz+VdEzRrVcGhrzucT39mFI1b9qfZFbhgjlQbUoheCY8QfWSeI3OtbXtX1gcpz5cpltJwYnITdwb1iRu8w2mxX/9UGaAVhnews3KlPpAvgq1/TWxdExJ1adyrkm1Oyac5d1ii0emk04v+K3Xgnpj16w8Jq2iYbpddiNW4C67F5Icim0OOK13JONKen+H2u7tHA6pNUTwbsKwDLqmBTaSFBdSJSnbkLug9YoRZJ7IuNRMa9l9ZMxOeHFHpnRfrTly2x72kv3shtwV556VdYXk8zdk6QynfBTjYvM7TC6542MVCzOkZYp2yeAcw5lllwVtTRNUW93GgAV6rxE+Y4x5Nf703C5/FwHtedLzpieuJnYsq/FEViWSXISd07IwyLcyq7IheStFeROuEBV2eA8LN5SF4TU505ZKLP7bJw3Zuvj3n88mrWLKlI6ntB1ekuQZtCxaYfAGC7bAOtdfWPxZ9k0Gffgwg2vFXXGFtuAj1SNdS+Ozi/AJxTsiUSkGQXVhkYw6Vp2GpqwmK6N1IeO6GnWTHD4iBvipOBNe8AWMRWdkWiHZE7xOeDLRp44qsNXkUnXZXTjjEMn4vGvPO6cZvVySsVP45Q+16aBqCSvPhH+D7+DTb0U71V9F6Wx4cXWPcPcI22QZ4fEjshLyWAqMNEsMkbWu7xKUK9HSceStMpJacGXJqNqsT/KrhoZnZCqPdWzSaXte3nzWYzgtnVwkbJxkOR73SzFtzyxGxnXN0IV80bXaRYLTJ8MiiaVTearwVYWrW/cb8P8oLzffWnw5k5SDvYe4+noNSs49kGiYUtHZiXcL/GVSLD7UVcnPRu3MbTUeD8Y3PaGWo6wLdW9ZfeYT0tfvreuioV5rdOkbfVYam/rFppdWerWECmf8wPlf17fd8+rlTzfPSTjo5TY4GZe588m3Q+V72bUQ7WndChWyoIYhmt4Ou47M70XDcL54umTkEgnXNYFU+qdLXiuq9HNVlqTD82FTMfbgeMIpWTb6M+YWvtp2Tq4dmbdpg/QrRB+9uVj15yZxhJh/9mODgoM1uYnkgwtyj7c9XefiVPmqQ7jKM5hlGE++fmQh+E3yh10ysYZTbBDlhFx16KgfjzY90cRE+Plvf20ytrDX5ytzctzPHWyMa10b7/tuldv8bJbiAizn4GHR2/udzHmESc3LemlnOrDfY+azelc7KQX0w0KP8cTEQYX275IPXdEm6sszXckSvEft5Am/OEX3tD99H0Y49YklkdINZg4pXh/6Diz8rjjIXlq4TN4PXBWuHlQx2Ca1hZUqxfa28Nye/cjSyAyelgp//+Lw4pzmRlSACu5P9Ue3EmlRC6Nw1dSgtU0yD6GulhjQai2OKbDx2wNO9NizLtsNFTnQUI1vun/LTnDTb9e8xaG3Kx4O5vJj1MzCaslZFZOG58p+cbOgVRyZN1rfF5LJWbc8N95P5eiAO0smcBn25xFuz0C/Koin4X6F76aVIXfRkjA8dCkzHliQ9mBXZz/aoscYRaOHRMdzdMANoWMMeaFzz6CHPLBPYye6cRLRGcOlKEzPMIiqxcr17JN9lc7ksB3ts5uOX8LW5EmO5obpJWGSdrL+atJDBcXVHXZ2TWJvrslsW+cGnnOCa04v+11ExXSeLjQrrqIaxsCRlow3gWTXsrZALilmNOBFB2oif0mSbyXR5yv+fd+qRKnpe3z4rg72JQ0+1Inn1S4ZJ6fx+b98mnuDtXa/fl3OTMEHfxAa8HtyoMytfAIzZNLs0tQfcKpX8nS+3O96dxRCLRvTVStW8ZtHb/o7VBPyBZmwPoXnfpjcYsZiMmGv8uNj7QlsyHXcstTcBFXCa35fkWsVzVTJv2+5Xv4Z86hLOuytW9buZYabuFpSB6XDVAkZvYvvozOYmHY6r1iHhSUiHEFkoYXVwlbFLShctO3H84JGGLfyyJYt/7eFPFNzYPOywtPByHBk3JtP4cljHbWPD3eRQx0jPhrGaVAvPkI9GjlMqRUTjGbFG4WU9YsLtwVkcx7Hg5yzSzHwckuTKnd1Ohk72xy9GXjiaDMkfJIKaJYPikvbbnE48XUflXBA8M+5sNlBd2aX4u2Zi09vVCfe0HS1eiP1zXZvLhDK14CaN6SUBEO0ADX/YAT2uJt2FtXoU8JkdW/HeWjWQk9Ri6aUboOKU1haX+3g9EluuMrlemHG3g2hYjRZYk1ZJH/K7SWHJ+fLX0XLzw03NOKM4l3O5VkE85Dsw3T3y/IJH5GKnDR5dY30WFVQ46bS9feE/GLzMQujUYn4ioqw4qj9Ckd+e/2LSZrRq8YpXj7t13p49mAnX7gFSxEnljRShVfKHsvdaeNSFZjNWnkrzL6zVxKP0tsS0dgJUHPDu37IiByDMxTvpECW7LPyzi25uRGc6n8ZXtp8Na8555xCE5mzQT6LxhMLTi4Qe84vCQfU3DQbzeJAlv6RmbN/S5LEezlHluMo38su/Suhj6rhmwOqMnHSFj1h2Kqtuv06qPRvzVujXaG4LwW3FYIlR9PNvqmh8RnQdMzl3izRpdjJeC/A6X/p31PawY+cLHumz98JpcNRXEvkL6iSb7cTXZj6HKPj4nMs4sp42q/1fi1JIhxbiPvSJ/QbuWP9k/qkgdv4gVwwbteOFkOS4hKlQ5l6O1wQaaowc0yQbWvhbnJ00ixpkmuwPLrJgV37WXQLVLZdTEot4dmOSu+NlOPZ5RL98kex/M3XvjhQpY/WPuopufUKarE+hyWbQBv3/ByyjWdSD51LqeV017n1G0kcz5lcwV0+WkQ+ta2h2+GKTgl9hhn6cE4ulHOqeCJ57St9HDycw8S/dOXm6Lm6gNQPqYkbNONuucm6+En2krqPHFEsc5YCog70r+0Xv/pj2pl73nQ8QZjYDbpXkEobF5pfpYBKf5NGMi2K3g+iBvv8ogfF67RVFO9TvB8vlcXS5Kd5VPnwf+EUU+XVkcISAAAAAElFTkSuQmCC\n",
      "text/plain": [
       "<PIL.PngImagePlugin.PngImageFile image mode=RGB size=64x64 at 0x7FC1D11E2550>"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "save_image(img, 'a.png')    #将Tensor保存成图片\n",
    "Image.open('a.png')         #读取图片"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'/home/zilong/Desktop/test/pytorch'"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pwd"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "可视化工具： tensorboard_logger, visdom "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Process is interrupted.\n"
     ]
    }
   ],
   "source": [
    "%%sh\n",
    "nohup python -m visdom.server"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'sinx'"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Connection is already closed.\n"
     ]
    }
   ],
   "source": [
    "import visdom\n",
    "\n",
    "vis = visdom.Visdom(env=u'test1')\n",
    "\n",
    "x = t.arange(1, 30, 0.01)\n",
    "y = t.sin(x)\n",
    "vis.line(X=x, Y=y, win='sinx', opts={'title': 'y=sin(x)'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "Exception in user code:\n",
      "------------------------------------------------------------\n",
      "Exception in user code:\n",
      "------------------------------------------------------------\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 141, in _new_conn\n",
      "    (self.host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 83, in create_connection\n",
      "    raise err\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 357, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 166, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 150, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1cd61c438>: Failed to establish a new connection: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 440, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 639, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py\", line 388, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1cd61c438>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/visdom/__init__.py\", line 446, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 112, in post\n",
      "    return request('post', url, data=data, json=json, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 58, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 508, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 618, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 508, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1cd61c438>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 141, in _new_conn\n",
      "    (self.host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 83, in create_connection\n",
      "    raise err\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 357, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 166, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 150, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1ccd8add8>: Failed to establish a new connection: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 440, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 639, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py\", line 388, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccd8add8>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/visdom/__init__.py\", line 446, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 112, in post\n",
      "    return request('post', url, data=data, json=json, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 58, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 508, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 618, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 508, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccd8add8>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 141, in _new_conn\n",
      "    (self.host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 83, in create_connection\n",
      "    raise err\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 357, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 166, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 150, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1ccd8a2e8>: Failed to establish a new connection: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 440, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 639, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py\", line 388, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccd8a2e8>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/visdom/__init__.py\", line 446, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 112, in post\n",
      "    return request('post', url, data=data, json=json, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 58, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 508, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 618, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 508, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccd8a2e8>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 141, in _new_conn\n",
      "    (self.host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 83, in create_connection\n",
      "    raise err\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 357, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 166, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 150, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1ccda7080>: Failed to establish a new connection: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 440, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 639, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py\", line 388, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccda7080>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/visdom/__init__.py\", line 446, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 112, in post\n",
      "    return request('post', url, data=data, json=json, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 58, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 508, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 618, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 508, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccda7080>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 141, in _new_conn\n",
      "    (self.host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 83, in create_connection\n",
      "    raise err\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 357, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 166, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 150, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1ccdb7978>: Failed to establish a new connection: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 440, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 639, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py\", line 388, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccdb7978>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/visdom/__init__.py\", line 446, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 112, in post\n",
      "    return request('post', url, data=data, json=json, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 58, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 508, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 618, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 508, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccdb7978>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 141, in _new_conn\n",
      "    (self.host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 83, in create_connection\n",
      "    raise err\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 357, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 166, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 150, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1ccda7400>: Failed to establish a new connection: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 440, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 639, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py\", line 388, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccda7400>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/visdom/__init__.py\", line 446, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 112, in post\n",
      "    return request('post', url, data=data, json=json, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 58, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 508, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 618, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 508, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccda7400>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 141, in _new_conn\n",
      "    (self.host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 83, in create_connection\n",
      "    raise err\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 357, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 166, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 150, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1ccd8a828>: Failed to establish a new connection: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 440, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 639, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py\", line 388, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccd8a828>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/visdom/__init__.py\", line 446, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 112, in post\n",
      "    return request('post', url, data=data, json=json, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 58, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 508, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 618, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 508, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccd8a828>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 141, in _new_conn\n",
      "    (self.host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 83, in create_connection\n",
      "    raise err\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 357, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 166, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 150, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1ccdb7208>: Failed to establish a new connection: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 440, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 639, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py\", line 388, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccdb7208>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/visdom/__init__.py\", line 446, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 112, in post\n",
      "    return request('post', url, data=data, json=json, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 58, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 508, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 618, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 508, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccdb7208>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 141, in _new_conn\n",
      "    (self.host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 83, in create_connection\n",
      "    raise err\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 357, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 166, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 150, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1ccd8a208>: Failed to establish a new connection: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 440, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 639, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py\", line 388, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccd8a208>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/visdom/__init__.py\", line 446, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 112, in post\n",
      "    return request('post', url, data=data, json=json, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 58, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 508, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 618, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 508, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccd8a208>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 141, in _new_conn\n",
      "    (self.host, self.port), self.timeout, **extra_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 83, in create_connection\n",
      "    raise err\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 601, in urlopen\n",
      "    chunked=chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 357, in _make_request\n",
      "    conn.request(method, url, **httplib_request_kw)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 166, in connect\n",
      "    conn = self._new_conn()\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connection.py\", line 150, in _new_conn\n",
      "    self, \"Failed to establish a new connection: %s\" % e)\n",
      "urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc1ccda7a90>: Failed to establish a new connection: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 440, in send\n",
      "    timeout=timeout\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py\", line 639, in urlopen\n",
      "    _stacktrace=sys.exc_info()[2])\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py\", line 388, in increment\n",
      "    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n",
      "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccda7a90>: Failed to establish a new connection: [Errno 111] Connection refused',))\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/visdom/__init__.py\", line 446, in _send\n",
      "    data=json.dumps(msg),\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 112, in post\n",
      "    return request('post', url, data=data, json=json, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/api.py\", line 58, in request\n",
      "    return session.request(method=method, url=url, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 508, in request\n",
      "    resp = self.send(prep, **send_kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/sessions.py\", line 618, in send\n",
      "    r = adapter.send(request, **kwargs)\n",
      "  File \"/home/zilong/anaconda3/lib/python3.6/site-packages/requests/adapters.py\", line 508, in send\n",
      "    raise ConnectionError(e, request=request)\n",
      "requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc1ccda7a90>: Failed to establish a new connection: [Errno 111] Connection refused',))\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'Visdom' object has no attribute 'updateTrace'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-26-5067d54709d0>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0mx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mt\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0marange\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m9\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m0.1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[0my\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0;36m9\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 8\u001b[0;31m \u001b[0mvis\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mupdateTrace\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mY\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mwin\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'polynomial'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'this is a new trace'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m: 'Visdom' object has no attribute 'updateTrace'"
     ]
    }
   ],
   "source": [
    "for ii in range(0, 10):\n",
    "    x = t.Tensor([ii])\n",
    "    y = x\n",
    "    vis.line(X = x, Y = y, win='polynomial', update='append' if ii>0 else None)\n",
    "    \n",
    "x = t.arange(0, 9, 0.1)\n",
    "y = (x**2)/9\n",
    "vis.updateTrace(X=x, Y=y, win='polynomial', name='this is a new trace')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "vis.image(t.randn(64, 64).numpy())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "保存Module和Optimizer对象时，应保存对应的state_dict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "odict_keys(['features.0.weight', 'features.0.bias', 'features.3.weight', 'features.3.bias', 'features.6.weight', 'features.6.bias', 'features.8.weight', 'features.8.bias', 'features.10.weight', 'features.10.bias', 'classifier.1.weight', 'classifier.1.bias', 'classifier.4.weight', 'classifier.4.bias', 'classifier.6.weight', 'classifier.6.bias'])"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from torchvision.models import AlexNet\n",
    "\n",
    "model = AlexNet()\n",
    "model.state_dict().keys()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "AlexNet(\n",
       "  (features): Sequential(\n",
       "    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))\n",
       "    (1): ReLU(inplace)\n",
       "    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)\n",
       "    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))\n",
       "    (4): ReLU(inplace)\n",
       "    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)\n",
       "    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n",
       "    (7): ReLU(inplace)\n",
       "    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n",
       "    (9): ReLU(inplace)\n",
       "    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))\n",
       "    (11): ReLU(inplace)\n",
       "    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)\n",
       "  )\n",
       "  (classifier): Sequential(\n",
       "    (0): Dropout(p=0.5)\n",
       "    (1): Linear(in_features=9216, out_features=4096, bias=True)\n",
       "    (2): ReLU(inplace)\n",
       "    (3): Dropout(p=0.5)\n",
       "    (4): Linear(in_features=4096, out_features=4096, bias=True)\n",
       "    (5): ReLU(inplace)\n",
       "    (6): Linear(in_features=4096, out_features=1000, bias=True)\n",
       "  )\n",
       ")"
      ]
     },
     "execution_count": 35,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "t.save(model.state_dict(), 'alexnet.pth')\n",
    "model.load_state_dict(t.load('alexnet.pth'))\n",
    "model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Adam (\n",
       "Parameter Group 0\n",
       "    amsgrad: False\n",
       "    betas: (0.9, 0.999)\n",
       "    eps: 1e-08\n",
       "    lr: 0.1\n",
       "    weight_decay: 0\n",
       ")"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "optimizer = t.optim.Adam(model.parameters(), lr=0.1)\n",
    "t.save(optimizer.state_dict(), 'optimizer.pth')\n",
    "optimizer.load_state_dict(t.load('optimizer.pth'))\n",
    "optimizer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "dict_keys(['optimizer', 'model', 'info'])"
      ]
     },
     "execution_count": 37,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 同时保存模型和优化器\n",
    "all_data = dict(optimizer = optimizer.state_dict(),\n",
    "               model = model.state_dict(),\n",
    "               info = u'optimizer and module')\n",
    "t.save(all_data, 'all.pth')\n",
    "\n",
    "all_data = t.load('all.pth')\n",
    "all_data.keys()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
